### ISSUE TITLE
Lỗi - BC sử dụng biên lai thu: xem tháng thì có biên lai mất nhưng xem quí năm thì không có

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#106]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92017`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Da liễu CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dalieu_phieutamung_bcmathoadon`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

   > _**QUYENBL**_: `Q0002` - _**KYHIEU**_: `DL2/20` - _**ThangKT**_: `10` _**ThangKT**_: `11` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Báo cáo Sử dụng biên lai thu
* Quyển biên lai: Q0002    - Ký hiệu: DL2/20
 số biên lai thống kê vào Mất
 - Tháng 10: 4
 - Tháng 11: 63
 - Năm: 0
 
-> Xem theo tháng thì thống kê có số biên lai mất xem theo năm thì không có!

-> BV đề xuất đưa phần biên lai mất vào phần tồn.
```
Tháng 10
![image](https://user-images.githubusercontent.com/96155021/205838846-1f4b3104-6acd-41e4-a94a-e57bee74f02f.png)
Tháng 11
![image](https://user-images.githubusercontent.com/96155021/205839287-4af2464c-5965-4c66-b967-3693de7b09fd.png)
Năm 2022
![image](https://user-images.githubusercontent.com/96155021/205839328-4c5bf881-ab68-448f-bbaf-d42e14342b6e.png)

Quyển Biên lai
![image](https://user-images.githubusercontent.com/96155021/205839065-1e07e4bd-7776-4b8b-9533-ab25398ace49.png)

**Comment by ongtrieuhau** [comment]
Phần này hổng phải lỗi nhé @le-an-87 , trước giờ phần mềm mình đang thiết kế theo nguyên tắc đó (vd, sử dụng 1,2....4,5 thì số 3 không có thực hiện lập và xóa thì sẽ tính là **mất**) còn báo cáo có số mất mà báo cáo năm lại không có, thì những số này đã sử dụng trong tháng khác rồi đó.


> -> BV đề xuất đưa phần biên lai mất vào phần tồn. 

=> Phần này nên tách riêng thành yêu cầu để chờ duyệt nhé

**Comment by le-an-87** [comment]
ok anh!
chuyển qua yêu cầu https://github.com/dh-hos/dhg.hospitalfees/issues/92
