### ISSUE TITLE
Yêu cầu - Cấp key sử dụng HDDT.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#110]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/01/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Huyện Tam Nông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Nhờ anh @ongtrieuhau cấp key sử dụng Hóa đơn điện tử của Viettel cho Trung Tâm Y Tế Huyện Tam Nông - 87004.

**Comment by nghivanbi** [comment]
@ongtrieuhau cấp key theo yêu cầu nhé.

**Comment by ongtrieuhau** [comment]
> @ongtrieuhau cấp key theo yêu cầu nhé.

`{"AtRow":46,"mabvbh":87004,"DateExpires":"2023-02-20","UseHddtBy":"Viettel","Trial":""}
=====DECODE=====
U2FsdGVkX1/egDAzyiFVw3UOI/k7cHsJnODelZhxAeA9MID4J+XLn1LN4TZ8DHNl8MXocD07UEGi5yMZhPLlzYiKxyKUS0KLZWtT6KZP4dcXvjftI39GeZwNSHyW2TxhGUk3kiBaHqIprj99c0K4OQ==`
