### ISSUE TITLE
Yêu cầu - Cấp quyền sử dụng HDDT-VIETTEL

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#111]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) ``
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

TTYT Thanh Bình đang xài HDDT của VNPT, giờ BV chuyển qua VIETTEL, yêu cầu cấp key sử dụng Hóa đơn điện tử VIETTEL của TTYT Thanh Bình - 87010.
TTYT Huyện Lấp Vò  thêm Cơ sỡ 2, xài chung nhà cung cấp với Cơ sở 1 là Viettel, chung mã số thuế, yêu cầu cấp key sử dụng HDDT Viettel cho Lấp Vò - 87197

**Comment by ongtrieuhau** [comment]
{"AtRow":20,"mabvbh":"87010","DateExpires":"2023-02-28","UseHddtBy":"Viettel","Trial":""}
=====DECODE=====
U2FsdGVkX1954BYK8iL1CZO4yQrNrn+JVvUMY6i+MAk5W43zHfLNC83jgeObYT/PgXj8yHTOLO89ntmmOYniel2oGWjkCdeiviqiwdCvxPNvrMxiJzJoOkuS2WlN25fFidQvb1i8EdvikJBQytNsdQ==

{"AtRow":64,"mabvbh":"87197","DateExpires":"2023-02-28","UseHddtBy":"Viettel","Trial":""}
=====DECODE=====
U2FsdGVkX1/ws0I0p4caxd6GpBEmBEWRRqpriyFZrMy1i7cKqEev26DtMWoUhVsDAtkTsUPyEkUlWxdpF3HeSBtlaUoSzpNQECN60DWRGK8Rnx4rgIDgZVO0D2A6Hm7jdZ92dU+v3QZqeIIQDdbMGA==
