### ISSUE TITLE
Yêu cầu - Cấp key sử dụng hóa đơn điện tử VIETTEL

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#112]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87196`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Huyện Thanh Bình CS2**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu cấp key sử dụng Hóa đơn điện tử **Viettel** cho TTYT Huyện Thanh Bình Cơ sở 2 - 87196

**Comment by nghivanbi** [comment]
@ongtrieuhau hỗ trợ nhé

**Comment by ongtrieuhau** [comment]
{"AtRow":65,"mabvbh":"87196","DateExpires":"2023-02-28","UseHddtBy":"Viettel","Trial":""}
=====DECODE=====
U2FsdGVkX18HJQzU1yqxmIcJAqAqA5A/z+GWEa48DABGU6wNn94tgUSEChw3uRABU2VrZBpUUdt4pXofNNV/Z2hnlEtWEuyB9OwFItIpWUjMb1o5sAst4tpZ5cHkOuZ36sryXXFKW9ev+LdEu5wyVw==
