### ISSUE TITLE
Yêu cầu - Cấp key sử dụng HDDT VNPT

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#113]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92124`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đồng Xuân**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu cấp key sử dụng Hóa đơn điện tử VNPT cho PK Đồng Xuân - 92124.
Hợp đồng đã ok hết.

**Comment by ongtrieuhau** [comment]
{"AtRow":66,"mabvbh":"92124","DateExpires":"2023-03-30","UseHddtBy":"Vnpt","Trial":""}
=====DECODE=====
U2FsdGVkX18czmOMZyCwExd6JK4VGPREGaerQpH2BbaoRva0rso54d1hH7xZq0lSXm4af5wmrul/CE1T/06ukUWiRyPvkMdzu/9q9uGh0SQZ0FWrUeEFwhIHB6yV63JDPMNtC15PjWNwwmh/R0fGUQ==
