### ISSUE TITLE
Yêu cầu - Bị mất nội dung trên form do độ phân giải.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#116]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhtri_st_2023_02_10`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Khi mở form Thu tự do, thì cái khung phiếu thu bị khuất mất, chỉnh độ phân giải có độ cao phải lớn 768 mới thấy được, còn nếu độ phân giải có độ cao từ 768 trở xuống là cái khung phiếu thu bị khuất mất.
Yêu cầu dời 1 số thông tin của đơn vị của BN qua bên khung trống còn dư phía bên phải.

![image](https://user-images.githubusercontent.com/99630883/218627804-c5ac1aee-0764-4176-9501-b198b9269bf2.png)

**Comment by ongtrieuhau** [comment]
Phần này cơ bản phần mềm đang theo chuẩn 768 này rồi, nên không thực hiện thay đổi theo chế độ [1. Gấp](https://github.com/dh-hos/dhg.hospitalfees/labels/1.%20G%E1%BA%A5p) được nhé

**Comment by lqbinh1987** [comment]
Vậy nhờ a @ongtrieuhau xem phân bố lại dùm em, vì máy ở BV màn hình chỉnh độ cao tối đa là 768 rồi mà vẫn không thấy hết nội dung.

**Comment by lqbinh1987** [comment]
Nhờ a @ongtrieuhau coi lạ dùm em chổ này, phiên bản cũ thì không bị, mà phiên bnr mới lại bị.
