### ISSUE TITLE
Lỗi - Ghi nợ bệnh nhân có BANT theo đợt

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#117]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTP Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dktp_ghino`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022089704` - _**2301019246**_: `MaKB` - _**MaBA**_: `N2023003170` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `49` - _**MaDV**_: `31` - _**ThangKT**_: `01-02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

 ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)
      

- [ ] Theo như giải thích của anh Hậu, thì đối với BANT theo đợt thì ghi nợ với điều kiện là BN đã kết thúc với xử trí là **Trốn viện**, nhưng phần mềm đang lỗi như chi tiết dưới đây:

- Bệnh nhân có BANT nhập viện lúc 19/01/2023, hiện chưa kết thúc BA, đến thời điểm hiện tại thi công nợ BN như hình 1.

Hình 1:
![image](https://user-images.githubusercontent.com/99630883/219259154-0cac32b1-f209-49ab-b116-5c912b6b37ee.png)

- Fees đăng nhập vô những ngày mà có phát sinh chi phí, vào chức năng **Ghi nợ** thì vẫn thấy tên BN đó, và thể hiện chi phí không đúng như hình 2.

Hình 2:
![image](https://user-images.githubusercontent.com/99630883/219259547-2810b797-5970-4ec9-a3ea-5965d3deec7f.png)

- Và trong form **Thu nợ** cũng hiển thị tên BN đó nhưng nhiều dòng giống nhau, số tiền cũng sai như hình 3.

Hình 3:
![image](https://user-images.githubusercontent.com/99630883/219259957-cd4338b5-aabb-4d26-aabe-d19f298feeab.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0410.2](https://github.com/dh-hos/dhg.hospitalfees/commit/6e5aa9d783b3cf4b47a1b615ba93656554ff4e9f)

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau 
Hiện chưa được nhe anh Hậu.
Đã cho xuất viện rồi nhưng vào form ghi nợ vẫn không thấy tên BN, BANT theo đợt và Nội trú đều bị.
Và form thu nợ cũng vẫn còn load trùng nhiều dòng của tên BN như hình báo phía trên.
