### ISSUE TITLE
Yêu cầu - Bổ sung dữ liệu báo cáo đối với BN thanh toán bằng hình thức chuyển khoản.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#119]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `70002`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Huyện Hớn Quản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_honquan_httt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Đề nghị trong menu **Báo cáo/Biên lai/Bảng kê biên lai thu** thêm cột dữ liệu **Hình thức thanh toán** của phiếu thu, vì BV đang xài tham số **hinhthucthanhtoan_macdinh**, mục đích để người dùng lọc báo cáo phiếu nào TM hoặc CK.
![image](https://user-images.githubusercontent.com/99630883/222663053-8f782f61-fc57-42c9-8861-0ebf47d71b9a.png)
![image](https://user-images.githubusercontent.com/99630883/222673136-c5c90d76-e473-47a2-88b2-8a89432154fc.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0410.1](https://github.com/dh-hos/dhg.hospitalfees/commit/5f047d47b97525f839582c2f2eacd67b7b23f3e0)
