### ISSUE TITLE
Lỗi - BC Bảng kê chi tiết theo bệnh nhân (Tổng hợp & nội trú) lệch tiền so với phiếu thu

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#121]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `89015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch AG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_ag_lech_stent`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2017054064` - _**MaKB**_: `2302017425` - _**MaBA**_: `2023002559` _**NgayKCB**_: `09/03/2023` - _**MaPhong**_: `E401` - _**MaDV**_: `06` - _**ThangKT**_: `03` - _**NamKT**_: `2023`

-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**SoBL**_: `VP32534` - _**SoNoiBo**_: `QT7..00698/03`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Lệch tiền giữa BC Bảng kê chi tiết theo bệnh nhân (Tổng hợp & Nội trú) so với phiếu thu

```
Phiếu thu
![image](https://user-images.githubusercontent.com/96155021/226828026-844dd171-7f9b-4a11-a62c-9f828d2a36b9.png)
Bảng kê nội trú
![image](https://user-images.githubusercontent.com/96155021/226828570-56e9c804-36b9-407d-8c6c-fde01e484214.png)
![image](https://user-images.githubusercontent.com/96155021/226828656-1e9c0629-c899-41f1-9e90-b7575ef1d56d.png)
Bảng kê tổng hợp
![image](https://user-images.githubusercontent.com/96155021/226828897-d061aa94-31ef-41cf-9fc3-d60efcd0e10a.png)

**Comment by le-an-87** [comment]
khi nào anh kiểm tra có bị mất dữ liệu trên máy chủ thì cho em hay em restore lại cho nhe!

**Comment by le-an-87** [comment]
an_timmach_ag_lech_stent
em có restore lại data rồi đó anh
em chép vào đây [/DuLieuCongTy/Database](https://dhsolutions.synology.me:5001/index.cgi?launchApp=SYNO.SDS.App.FileStation3.Instance&launchParam=openfile%3D%252FDuLieuCongTy%252FDatabase%252F) luôn rồi nhe anh (an_timmach_ag_lech_stent)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0412.2](https://github.com/dh-hos/dhg.hospitalfees/commit/4d9b0d0eb14bb0d549a4b31594c349f0b0a514ad)

`Kết quả bị lệch vài đồng là do cách làm tròn nhé có gì thông tin với bệnh viện nhé` @le-an-87

**Comment by le-an-87** [comment]
chổ này thiếu cấu trúc mô tả https://github.com/dh-hos/Mo-ta-he-thong/issues/22
chờ cập nhật cấu trúc xong mới kiểm tra đc nhe anh!

**Comment by le-an-87** [comment]
đã fix!
