### ISSUE TITLE
Lỗi - Cách tính số tiền BH thanh toán và BNCCT khi bệnh nhân có miễn cùng chi trả trả thuốc

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalfees#131]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **2/6/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_lechbncct_02_tongket_fees`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/OgjJsDqcB)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `18025645` - _**MaKB**_: `MaKB` - _**MaBA**_: `23002110` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `06` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `G3.01.1358.22` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Cách tính chi phí thuốc+VTYT khi bệnh nhân bệnh nhân có toa thuốc trước ngày miễn cùng chi trả nhưng có toa trả sau ngày miễn cùng chi trả
-> Cho em hỏi cách tính chi phí trường hợp này tính như thế nào? thống nhất cách tính chi phí trong trường hợp này

Mô tả Mo.ta.ghi.nhan.muc.huong.100.khi.ap.ngay.mien.chi.tra.-.27-02-2020 không ghi rõ trường hợp này.

Phần mềm Fees 
- Khi bệnh nhân có toa xuất thuốc trước ngày hưởng miễn cùng chi trả và toa trả thuốc sau ngày miễn cùng chi trả thì phần mềm tính tiền BNCCT (80%) của toa xuất, rồi mới trừ số tiền thuốc trả (100%)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/fd88b17d-ed57-4fe2-a680-3d570ab1cc14)

Phần mềm Treatment tính tương tự như Fees 
- Khi bệnh nhân có toa xuất thuốc trước ngày hưởng miễn cùng chi trả và toa trả thuốc sau ngày miễn cùng chi trả
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/fb353673-9738-44f8-a10f-b64ce84fdb78)

Phần mềm Reports 
- Khi bệnh nhân có toa xuất thuốc trước ngày hưởng miễn cùng chi trả và toa trả thuốc sau ngày miễn cùng chi trả thì Reports cấn trừ số lượng trước rồi mới tính tiền BNCCT
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/bee5494c-d622-43d5-b4f2-bb18947c9711)

Phần mềm Admin 
- Khi bệnh nhân có toa xuất thuốc trước ngày hưởng miễn cùng chi trả và toa trả thuốc sau ngày miễn cùng chi trả thì Admin cấn trừ số lượng trước rồi mới tính tiền BNCCT
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/811a8eb1-2774-492a-b691-e58b26d047a6)

**Comment by vuongdh** [comment]
@chauthanhtra số tiền bn trả 51.200 là đúng hén, vì toa thuốc này nằm ngoài đợt miễn

**Comment by vuongdh** [comment]
@chauthanhtra toa thuốc trả nằm trong đợt miễn nhưng không có thuốc nào để cấn trừ

**Comment by chauthanhtra** [comment]
Alo anh @vuongdh 
Như trường hợp này toa xuất nằm trong tháng 5 trước ngày chứng nhận miễn nhưng hiện tại qua tháng rồi thì không trả thuốc lùi ngày vào tháng cũ được . Nếu vậy thì tính ra chi phí bị sai
(nếu tính như hiện tại thì xuất bằng với trả thì có bị âm số tiền không)

Hiện tại mỗi phần mềm tính mỗi khác. Cần có mô tả cách tính chi phí chung để các phần mềm khớp với nhau

**Comment by vuongdh** [comment]
@chauthanhtra phần nào tính sai thì tính phần đó đi em, chổ anh bị sai là ko hiển thị phần âm lên (phần âm là khúc được miễn đó em) kaka
