### ISSUE TITLE
Lỗi - BC bảng kê biên lai thu không load được tiền vào cột CHI PHÍ (NHÀ THUỐC) (phiếu thu chức năng THUỐC NT)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#132]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_ct_vpnt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/dkFJmcZdx)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `19008720` - _**MaKB**_: `2306015561` - _**NgayKCB**_: `20/06/2023` - _**ThangKT**_: `06` - _**NamKT**_: `2023`
   > _**Soctvp**_: `VI8.00001/06`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Fees phiên bản ngày 06/06/2023
khi thực hiện thu tiền nhà thuốc bằng chức năng THUỐC NT
-> BC Bảng kê biên lai thu không thống kê vào cột CHI PHÍ (NHÀ THUỐC)

```
chức năng thu THUỐC NT
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/6f1879c7-494d-4164-a3ad-1018cded2362)

BC Bảng kê biên lai thu
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/62fe9c21-c859-4a70-abd9-7c17b1b5deb0)

**Comment by ongtrieuhau** [comment]
Cập nhật bản mới này, có chỉnh lỗi này rồi [3.23.0908.1](https://github.com/dh-hos/dhg.hospitalfees/commit/c19feb0cea6afcbe06e1f052cce4bfa17fec4072)
