### ISSUE TITLE
Yêu cầu - MỞ CHỨC NĂNG HDDT CHO PHÒNG KHÁM ĐA KHOA ĐỒNG TÂM

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalfees#133]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77155`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA ĐỒNG TÂM**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hỗ trợ mở chức năng HDDT cho đơn vị mới đang triển khai đã ký hợp đồng :
77155 - PHÒNG KHÁM ĐA KHOA ĐỒNG TÂM

**Comment by nghivanbi** [comment]
Kết nối hóa đơn điện tử với Viettel nhé @ongtrieuhau

**Comment by ongtrieuhau** [comment]
Cho em thông tin thời hạn của phần kết nối này @nghivanbi

**Comment by nghivanbi** [comment]
Hiện tại đã ký hợp đồng thuê 3 tháng đến 30/09/2023

**Comment by ongtrieuhau** [comment]
{"AtRow":67,"mabvbh":"77155","DateExpires":"2023-09-30","UseHddtBy":"Viettel","Trial":""}
=====DECODE=====
U2FsdGVkX1+ONpVjYDRt6ai2+MnbF6GESx1NQCQ9UO2v46m5R2evJcSoQRVcVRZXg9uklj3Gv3BLFGTZjECqpZwTfcwphCx9jJJMrZzLU5ZTQF86pjs12S1KqzSwttyw5WJ4sr3q3FY10WkSvVm/hA==

**Comment by nqhoa1005** [comment]
Em add key chưa được nhé anh Hậu
Check và cấp lại dùm em
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/130281806/86535929-cc10-46c2-9353-213094c59b16)

**Comment by ongtrieuhau** [comment]
Thông tin dữ liệu nhé

**Comment by nqhoa1005** [comment]
tên dữ liệu : hoa_dongtam_23062023
em vừa restore xong

**Comment by ongtrieuhau** [comment]
Key mới nhé: @nqhoa1005  
`U2FsdGVkX1+zt3aT24hjRweoQGO97Vux16/XU75GbaLkgeByOTHut4PNZwewx5oHm6PC5AAdHN5z+nUfn61fR3WqvvbejOXY94X+4SEy8z1+n9shdw7X2six9f8l3QgGgVC4P1CcFhD+OPamkyiFOA==
`

![image](https://github.com/dh-hos/dhg.hospitalfees/assets/58720300/592ee643-5c50-41f5-9d7b-fc7ed0e1ea28)

**Comment by nghivanbi** [comment]
Hạn anh mới cấp cho nó tới 30/06/2023, có ảnh hưởng tới key HDDT à?

**Comment by ongtrieuhau** [comment]
> Hạn anh mới cấp cho nó tới 30/06/2023, có ảnh hưởng tới key HDDT à?

2 chức năng này tách bạch nhau nhé a, nên hông ảnh hưởng.

**Comment by nqhoa1005** [comment]
key ok
