### ISSUE TITLE
Yêu cầu - Đổi dấu phân cách phần ngàn, phần triệu,.. số tiền trên phiếu thu và Lý do thu thành dấu ( . ) chấm

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalfees#136]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/7/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phước Long BL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phuoclong_fees_dauphanngan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/oglAi1zAv)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Data ngày 07/07/2023

BV Phước Long BL yêu cầu đổi dấu phân cách phần ngàn, phần triệu của số tiền trên phiếu thu thành dấu chấm ( . ) thay cho dấu phẩy ( , ) như hiện tại.
- Hiện tại không tìm thấy tham số và không chỉnh trong thiết kế phiếu thu được

![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/2ec5f03f-33c6-442f-a372-73b7bcb3629d)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/6b9604eb-9359-4d0b-b94a-fc8937f678b2)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/92f1f5be-0cbd-4d25-ad99-33cb3c02db76)

**Comment by nghivanbi** [comment]
@ongtrieuhau cho này có khó khăn gì không?

**Comment by ongtrieuhau** [comment]
Cái này yêu cầu cụ thể thế nào? Phiếu nào? Chức năng nào?

**Comment by chauthanhtra** [comment]
BV yêu cầu đổi dấu phân cách phần ngàn, phần triệu thành dấu chấm ( . ) của số tiền trên tất cả các mẫu phiếu thu BH, DV (đơn giá, thành tiền,...) và phần số tiền ở phần lý do thu và hóa đơn điện tử

**Comment by ongtrieuhau** [comment]
Trường hợp này có 2 phần:

1. Thứ nhất: phiếu in bằng hóa đơn điện tử thì có chức năng để option lại khi thực hiện đưa lên cổng HĐĐT
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/58720300/a0ca4929-893d-471d-91b3-a809ff8ca11a)

2. Thứ hai: Phiếu thu nội bộ in bằng Fees, có thể chỉnh lại do đây là phiếu thu tự in có thể điều chỉnh lại. Đây là cách thực hiện trên trang thiết kế. 
`Hàm để thay đổi dấu , thành dấu .`
[ChangeDotToComma.cs.txt](https://github.com/dh-hos/dhg.hospitalfees/files/12567827/ChangeDotToComma.cs.txt)

![image](https://github.com/dh-hos/dhg.hospitalfees/assets/58720300/71ff16ea-5638-4c47-bbd2-0b92d205a121)
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/58720300/2d8e83c1-1bf5-4670-8804-8deedfce2841)
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/58720300/abc0f18e-bc3d-4a85-a44f-f857482fc52e)
