### ISSUE TITLE
Lỗi - Thu tiền nội trú thể hiện sai chi phí thu thêm

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalfees#140]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_timmachct_fees`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/t2QqCiahd

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `18035242` - _**MaKB**_: `23003641` - _**MaBA**_: `MaBA` _**NgayKCB**_: `18/09/2023` - _**MaDV**_: `17` - _**ThangKT**_: `09` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Trên dữ liệu Hóa đơn xóa Chi phí thể hiện cột thu bảng congno

Cột thu và nock bảng congno bị sai chi phí

```
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/98437757/ea829533-3f83-4b3f-83d6-431a1ae0c42e)

![image](https://github.com/dh-hos/dhg.hospitalfees/assets/98437757/a9da6788-2ee7-4616-a1fd-72f67942c950)

![image](https://github.com/dh-hos/dhg.hospitalfees/assets/98437757/6621e324-f24d-4544-9413-4987db21bf36)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0605.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406051-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406051-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406051-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Hỗ trợ kiểm tra Đã có phiếu thu sử dụng tiền tạm ứng của bệnh nhân thì không cho phép xóa phiếu này

- ![](https://i.imgur.com/OSbEZqV.png)

- 🐛: Hỗ trợ Lỗi Thu tiền nội trú thể hiện sai chi phí thu thêm

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/140

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by ongtrieuhau-dh** [comment]
Phần này do dữ liệu cũ rồi, nên sẽ hỗ trợ để tránh trường hợp này xảy ra thêm. Phần chỉnh dữ liệu nếu bệnh viện cần thì nhờ hỗ trợ chỉnh lại cho đúng. 
Nguyên nhân là do lập phiếu chi rồi, lập phiếu thu (lúc này phiếu thu đã sử dụng tạm ứng của bệnh nhân để cấn trừ chi phí), rồi đi xóa phiếu chi này đi, nên xảy ra tình trạng như trên.

**Comment by minhduc2it** [comment]
Đã test chức năng chặn xóa phiếu tạm ứng khi đã lập phiếu thu ok
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/98437757/17400eda-3a28-494d-af30-bba7d5598a5c)

Test các chức năng cơ bản khác chưa ghi nhận bất thường
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/98437757/3509383f-eb86-4616-b713-b47dd0a33827)

![image](https://github.com/dh-hos/dhg.hospitalfees/assets/98437757/ffd0caa1-7cc5-4243-b05b-761224dd9569)
