### ISSUE TITLE
Lỗi - Gò Vấp - không thể in bảng kê khi đã hoàn tất thu tiền, lỗi tính cùng chi trả BN

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalfees#141]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79035`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN QUẬN GÒ VẤP**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvgovap_122023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023113255` - _**MaKB**_: `2312018880` - _**MaBA**_: `MaBA` _**NgayKCB**_: `23/08/2023` - _**MaPhong**_: `225` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trường hợp này thuốc có áp giá BHYT
Em kiểm tra tổng tiền BH chưa vượt mức cùng chi trả, BN chỉ phát sinh số tiền tự trả của thuốc là 79,600
Nhưng pinter tính 5% cộng vào nên không cho in bảng kê.
ca này còn treo thuốc tại kho cần gấp
Anh Hậu check dùm em

![Uploading image.png…]()

**Comment by lqbinh1987** [comment]
Nhờ Anh @ongtrieuhau coi lỗi Fees chổ này dùm em.
Fees không tính được ngưỡng tính % đồng chi trả, thuốc có áp tỷ lệ thanh toán và áp giá BHYT.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/6e248104-d555-497d-956f-6c0532022c7c)

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau coi chổ này gấp dùm em, BV phàn nàn quá chời rồi.

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupFees.v3.24.0129.1.msi](https://gofile.me/78TQg/E2sIAZoHi)
