### ISSUE TITLE
Lỗi - Phiếu thu cls tự do sai tổng tiền thu (BV Phong Điền)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#150]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phongdien_tienphieuthu_09012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phongdien_tienphieuthu_09012024`](https://gofile.me/78TQg/3iuVsgeMx)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000444` - _**MaKB**_: `2401002977` - _**NgayKCB**_: `09/01/2024` - _**MaPhong**_: `22` - _**MaDV**_: `03` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**SoCTthu**_: `V11.T0005/01`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng cls tự do form thu tiền bệnh nhân ngoại trú:
- khi thực hiện chỉ định cls có sử dụng CHỨC NĂNG TÌM KIẾM cls phần mềm tính tổng tiền thu không đúng
=> lệch tổng tiền thu so với tổng tiền các cls cộng lại.

** Như trường hợp bên dưới
- thực hiện tìm kiếm và chỉ định cls CH249 có giá 220.000
- Tiếp tục tìm kiếm đánh mã cls để tìm và chỉ định thêm 2 cls CA27 và CA25
=> phần mềm vẫn hiển thị tiền thu là 220.000 (không có cộng tiền cls CA27 và CA25)
==> tổng tiền phiếu thu bị sai
```
khi thực hiện chỉ định
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/3fc2a6ce-f417-4788-854c-5369a7d14de2)
Kiểm tra phiếu thu sai tổng tiền
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/11d906d9-8118-40d1-ac29-4d24c33c9c83)

**Comment by ongtrieuhau-dh** [comment]
uh, để kiểm nhé
