### ISSUE TITLE
Lỗi - Báo cáo chi tiết theo dịch vụ không tách chi phí dịch vụ sang tab hóa đơn (BV Phụ Sản CT)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#157]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_phieuthu_17012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_phieuthu_17012024`](https://gofile.me/78TQg/GafmHOBi9)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023109659` - _**MaKB**_: `2312006765` - _**MaBA**_: `022142` _**NgayKCB**_: `16/12/2024` - _**MaPhong**_: `ĐTTYC_KHU C` - _**MaDV**_: `25` - _**ThangKT**_: `12` - _**NamKT**_: `2023`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `GI78`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân sử dụng cls mã GI78 check dịch vụ đã thu tiền
-> báo cáo Chi tiết - theo dịch vụ và tổng hợp theo dịch vụ không tách được sang tab hóa đơn

```
Phiếu thu bệnh nhân
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/6a8224fb-47f0-4637-a8f6-9d82df5f86c6)
Báo cáo tab biên lai
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/886ba3c5-d4fe-425d-b009-c7e7324e3371)
BC tab hóa đơn không thống kê được cls dịch vụ
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/90d03c7f-328b-4c23-9b1d-0542bd72ca33)

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupFees.v3.24.0203.2.msi](https://gofile.me/78TQg/xmy33vwdr)

**Comment by le-an-87** [comment]
alo anh @vuongdh chổ này em test thấy khi chỉ định cls có thao tác check vào dịch vụ đối với đối tượng 06 thì không tính được tiền chênh lệch nhe anh
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/59596c45-b69c-45b6-b0f9-3d4f7a77336d)
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/f564e0c6-9aa6-45c8-8994-fbad5167bcda)

**Comment by le-an-87** [comment]
data: an_phusan_phieuthu_17012024
mã khoa: 25
mã bệnh án: 000005
tháng kt = 01
năm kt = 2024

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.02.06v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
Chổ tiền chênh lệch hiện tại form vẫn cho nhập và lưu được chổ này nếu đơn vị nào cần chỉnh thì bắt riêng đi anh @vuongdh.
đơn vị nào không cần chỉnh anh khóa lại đừng cho nhập nhe. để nhập sai rồi không biết lỗi do phần mềm hay ng dùng.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/c8e7ba99-9f90-467b-b84c-bd9b19d96178)

**Comment by vuongdh** [comment]
ok

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.02.06v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/3d9d1780-0e87-4007-b4df-ab69ebd0724b)
chưa được anh ơi

**Comment by vuongdh** [comment]
[Test lại bảng này nhé](https://gofile.me/78TQg/eVw21gWG9)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.02.06v4 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
+ Fees đã tách hóa đơn theo yêu cầu bệnh viện.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/0166491d-73b5-40e3-8293-fe56c8bd8873)
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/b0ac1509-199f-4615-8155-baa8d77185d0)

+ Treatment đã ghi nhận đúng tiền chênh lệch khi check dịch vụ.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/8db87904-ece9-4840-baf7-1b98d6b57b8c)
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/ed4937dd-75e9-42f8-8791-c9c4cdad49ee)
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/d2d8e7e3-a1ba-4464-a12b-1215dbae84a7)
+ Prescription
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/a10b041e-a75e-4c46-961a-e243b0e4a02b)
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/e46627f1-a8c1-40ed-a227-391d1b61d986)

** Dữ liệu ghi nhận toa thuốc tủ trực
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/5adea2dc-6a52-436e-8459-246758f5ff4a)
