### ISSUE TITLE
Lỗi - Chưa đến ngưỡng thu nhưng vẫn thu được % cùng chi trả.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#159]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvq12_saicct2`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024011505` - _**MaKB**_: `2402015298` - _**MaBA**_: `MaBA` _**NgayKCB**_: `20/02/2024` - _**MaPhong**_: `D.02` - _**MaDV**_: `09` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN thu tiền chênh lệch công khám xong(hình 1), BS chỉ định thêm CLS khác, nhưng tổng chi phí BHYT chưa vượt ngưỡng thu nhưng Fees vẫn tihs được % cùng chi trả của BN, lập phiếu thu đc luôn(Hình 2), em có test thử nhiều cách nhưng ko làm được ra lỗi như vậy, dữ liệu trích về nếu chỉ cần xóa bỏ phiếu thu cùng chi trả là phần mềm lại tính đúng lại.

**Hình 1:**
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/e133840f-292e-45bd-bbf5-5240482c58d4)

**Hình 2:** 
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/dc0ceafa-826f-47cd-89e0-4ca2c09ec7b6)

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau coi tranh thủ chổ này dùm em nhe anh, ở BV nó bị hối quá, liên quan đến tiền thu của BN nên kế toán nó lu bu quá.

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupFees.v3.24.0220.1.msi](https://gofile.me/78TQg/2FyV0tQeu)

**Comment by ongtrieuhau-dh** [comment]
Cái này xong chưa @lqbinh1987

**Comment by lqbinh1987** [comment]
Em đang test sơ sơ lại anh, vì dl về máy em thì nó không bị

> Cái này xong chưa @lqbinh1987
