### ISSUE TITLE
Lỗi - Sai địa chỉ trên phiếu thu so với địa chỉ bệnh nhân (BV Phụ Sản CT)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#160]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản TPCT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_diachiphieuthu_26022024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_diachiphieuthu_26022024`](https://gofile.me/78TQg/eB2KP9Ais)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024007606` - _**MaKB**_: `2402008721` - _**MaBA**_: `002823` _**NgayKCB**_: `25/02/2024` - _**MaPhong**_: `` - _**MaDV**_: `07` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**SoCT_thu**_: `T11..01991/02`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh viện báo phiếu thu đã lập sai địa chỉ so với địa chỉ của bệnh nhân.
--> hiện tại phần mềm cho tự nhập hoặc tự động lấy thông tin từ phiếu thu củ.

1. Đề nghị ghi nhận nhật ký tài khoản nào thay đổi thông tin khi lập phiếu thu. -> để xác định ai thay đổi thông tin hoặc lỗi do phần mềm.
2. Không lấy lại thông tin củ hoặc có option cho bv tự chọn và phải ghi nhận nhật ký.

```
Phiếu thu
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/960865e3-fbf6-48fc-b1c1-ea17c53edcaa)
Địa chỉ bệnh nhân
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/715e50e4-b8ee-4a04-96e1-4e4d0d067707)

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupFees.v3.24.0304.1](https://gofile.me/78TQg/Gmddedpzq)

- Cập nhật bản mới và theo dõi xem còn bị trường hợp này nữa hông, vì lỗi nay chưa biết nguyên nhân do đâu, chỉ đoán nguyên nhân là do lúc lập phiếu thu mới, nhưng những chứng từ của bệnh nhân trước đó còn nằm trong danh sách nên mới gây lỗi.
- Hỗ trợ kiểm tra lại mã bệnh nhân khi lấy lại thông tin chứng từ cũ (cùng mã bệnh nhân mới thực hiện thêm lại)
- Những yêu cầu phát sinh thêm, thì nhờ @le-an-87 lập yêu cầu nhé, vì cái issue này lỗi, nên hiện tại chỉ hỗ trợ phần lỗi ghi ngờ phát sinh thôi.

**Comment by le-an-87** [comment]
Vậy để em gửi Bản này cho bv sử dụng và nhờ bệnh viện theo dõi nếu có lỗi thì em sẽ báo lại.
