### ISSUE TITLE
Lỗi - Cách tính số tiền BH thanh toán và BNCCT khi bệnh nhân có miễn cùng chi trả trả thuốc

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalfees#163]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **2/6/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_lechbncct_02_tongket_fees`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/OgjJsDqcB)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `18025645` - _**MaKB**_: `MaKB` - _**MaBA**_: `23002110` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `06` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `G3.01.1358.22` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Cách tính chi phí thuốc+VTYT khi bệnh nhân bệnh nhân có toa thuốc trước ngày miễn cùng chi trả nhưng có toa trả sau ngày miễn cùng chi trả
-> Cho em hỏi cách tính chi phí trường hợp này tính như thế nào? thống nhất cách tính chi phí trong trường hợp này

Mô tả Mo.ta.ghi.nhan.muc.huong.100.khi.ap.ngay.mien.chi.tra.-.27-02-2020 không ghi rõ trường hợp này.

Phần mềm Fees 
- Khi bệnh nhân có toa xuất thuốc trước ngày hưởng miễn cùng chi trả và toa trả thuốc sau ngày miễn cùng chi trả thì phần mềm tính tiền BNCCT (80%) của toa xuất, rồi mới trừ số tiền thuốc trả (100%)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/fd88b17d-ed57-4fe2-a680-3d570ab1cc14)

Phần mềm Admin 
- Khi bệnh nhân có toa xuất thuốc trước ngày hưởng miễn cùng chi trả và toa trả thuốc sau ngày miễn cùng chi trả thì Admin cấn trừ số lượng trước rồi mới tính tiền BNCCT
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/811a8eb1-2774-492a-b691-e58b26d047a6)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0607.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406070-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406070-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406070-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi trường hợp thuốc trả và thuốc đánh toa khác chi phí miễn chi trả

- ![](https://i.imgur.com/MeBxYX1.png)

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/163

- 📕: Xử lý kiểm tra nếu cphi_mienct của thuốc trả, không có trong thuốc đánh, thì xử lý giống thuốc đánh toa_

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- Fees kiểm tra đã thống nhất với Admin và Reports : cấn trừ số lượng trước rồi tính chi phí. 

![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/8312dfd1-85d0-4a13-9f9f-0da4cc90c86f)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/2424f14d-61a5-4177-b387-35eda449a0ad)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/e1401ab3-1b02-417a-917a-2313ae242f59)


- Chờ thống nhất cách tính chi phí với Treatment : https://github.com/dh-hos/dhg.hosptaltreatment/issues/231

**Comment by ongtrieuhau-dh** [comment]
Sẽ mô tả thực hiện để cấn trừ đúng lại nhé

**Comment by nghivanbi** [comment]
Đã cho thực hiện mỗ tả xử lý.
