### ISSUE TITLE
Lỗi - Phiếu thu cls tự do sai tổng tiền thu (BV Phong Điền)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#165]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phongdien_tienphieuthu_09012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phongdien_tienphieuthu_09012024`](https://gofile.me/78TQg/3iuVsgeMx)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000444` - _**MaKB**_: `2401002977` - _**NgayKCB**_: `09/01/2024` - _**MaPhong**_: `22` - _**MaDV**_: `03` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**SoCTthu**_: `V11.T0005/01`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng cls tự do form thu tiền bệnh nhân ngoại trú:
- khi thực hiện chỉ định cls có sử dụng CHỨC NĂNG TÌM KIẾM cls phần mềm tính tổng tiền thu không đúng
=> lệch tổng tiền thu so với tổng tiền các cls cộng lại.

** Như trường hợp bên dưới
- thực hiện tìm kiếm và chỉ định cls CH249 có giá 220.000
- Tiếp tục tìm kiếm đánh mã cls để tìm và chỉ định thêm 2 cls CA27 và CA25
=> phần mềm vẫn hiển thị tiền thu là 220.000 (không có cộng tiền cls CA27 và CA25)
==> tổng tiền phiếu thu bị sai
```
khi thực hiện chỉ định
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/3fc2a6ce-f417-4788-854c-5369a7d14de2)
Kiểm tra phiếu thu sai tổng tiền
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/11d906d9-8118-40d1-ac29-4d24c33c9c83)

**Comment by le-an-87** [comment]
https://github.com/dh-hos/dhg.hospitalfees/issues/150#issuecomment-1882380370

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0601.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406012-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406012-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406012-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi không tính lại thành tiền của phiếu thu

![](https://i.imgur.com/C86yIGH.png)

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/165

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Để em test lại. lỗi do em!

**Comment by le-an-87** [comment]
Còn lỗi trường hợp xóa cls nhe anh.
*Trường hợp cho 2 cls
-> chọn cls cần xóa -> lick chuột vào chổ khác -> chọn xóa
=> lúc này phần mềm sẽ không tính được tiền thu và thành tiền
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/4028f777-871a-4335-a1e5-77075dfa40c4)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/70aadddc-6ba1-4030-805c-0f2cfd8a80c7)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0605.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406050-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406050-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406050-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi không tính tiền lại khi xóa chi tiết CLS

- ![](https://i.imgur.com/XPMWjQ2.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/165

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/d5d5ebe2-c410-4aac-9a6c-34233032eee9)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/932733a2-ccd0-4394-b07a-6775c97a9f6b)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/4b6fdb6e-a723-4a95-9540-bcab1d3d4215)
