### ISSUE TITLE
Lỗi - Phiếu thu mẫu mặc định bị mất khuất địa chỉ đơn vị

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#171]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `60152`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Phúc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamphuc_phieuthu_kochinh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/2x3PXy8l2)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023018369` - _**MaKB**_: `2307001079` - _**NgayKCB**_: `05/07/2023` - _**MaPhong**_: `KNO1` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2023`
   > _**Soct**_: `V32.00434/07`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Phiếu thu mặc định bị khuất địa chỉ đơn vị ( Không hiển thị hết tên tỉnh)
```
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/e56d7dba-f0e2-4a45-8789-92f0175d7218)

**Comment by ongtrieuhau-dh** [comment]
Cái này Fees đã có chức năng phiếu thu tự thiết kế rồi, nên nhờ @le-an-87 chuyển qua phiếu thu tự thiết kế để hỗ trợ bệnh viện luôn, để bên mình khỏi phải chỉnh những mẫu cũ này nữa, cũng theo hướng chung của công ty là chuyển dần sang tự thiết kế các mẫu. 
PS: nhờ @nghivanbi duyệt theo yêu cầu này giúp.

**Comment by nghivanbi** [comment]
@le-an-87 hỗ trợ bệnh viện chuyển mẫu tự thiết kế nhé.

**Comment by le-an-87** [comment]
chổ này 2 nút in trên form thu tiền này in ra 2 mẫu khác nhau.
- nếu sử dụng tham số hosfees.phieuthutuin = 1 thì sẽ in chung 1 mẫu.
- mẫu thiết kế củ cũng không sử dụng được.
anh xem lại giùm em nhe
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/badbc845-923a-4830-ba40-7ce9419f53f9)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/73049aed-347e-4043-9a64-96cb5241549a)

Hình này là em chỉnh tham số lại =0 nó không load được cái thiết kế củ luôn
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/b0b45cba-790a-48e7-bff8-b71f77cf1c34)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/37a3d1dc-1b25-4148-8749-23f495a46700)

nếu chuyển qua thì anh cho 2 mẫu này thiết kế riêng nhe anh

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0525.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405250-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405250-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405250-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Mở rộng text in địa chỉ trên phiếu thu

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/171

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Địa chỉ đơn vị đã fix rồi!

Test phát hiện thêm địa chỉ bệnh nhân nếu dài quá cũng không hiển thị hết,
anh fix thêm chổ này luôn nhe anh!
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/f70655b0-49e5-4d38-a675-0c33941227a2)

**Comment by ongtrieuhau-dh** [comment]
ok, @lequocthong29 fix tiếp anh chỗ này nhé

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0527.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405270-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405270-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405270-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi mất % lý do thu

- 🐛: Fix xuống dòng địa chỉ trên phiếu thu

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/171

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/183

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0528.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405280-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405280-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405280-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix xuống dòng địa chỉ trên phiếu thu

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/171

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/597a5f44-4501-4143-8c41-435acd269670)

![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/d20dd6dc-c3b2-4840-8a37-6f5abd8f7335)
