### ISSUE TITLE
Lỗi - Báo cáo Chi tiết và tổng hợp theo dịch vụ khi xuất theo loại chi phí viện phí lấy luôn chi phí nội bộ (bv Phụ sản)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#173]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_chitiettheodichvu_06032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_chitiettheodichvu_06032024`](https://gofile.me/78TQg/zgOV5vFw7)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024017242` - _**MaKB**_: `2403002840` - _**NgayKCB**_: `05/03/2024` - _**MaPhong**_: `20` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DO25`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Báo cáo bảng kê chi tiết theo dịch vụ và tổng hợp theo dịch vụ
-> khi xuất chọn loại phí "chỉ viện phí" vẫn thống kê các cls thuộc chi phí nội bộ.
```
Cls DO25 thuộc chi phí nội bộ và thu tiền phiếu thu nội bộ
báo cáo chỉ có viện phí vẫn load lên
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/01f1a738-016b-4603-aa23-b2e39b478f14)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/1c774978-0919-41e1-ab6e-264714c9097d)

báo cáo theo loại chi phí nội bộ
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/d6f95c7d-915b-4b97-83dc-6f7c15f618a2)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/40448459-6a70-44f8-8945-f6b8eb8bd9ca)

dmcls
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/563ae4f1-4887-44f2-92b7-d2f19650e0ef)

**Comment by ongtrieuhau-dh** [comment]
Đã tiếp nhận nhé

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupFees.v3.24.0317.1.msi](https://drive.google.com/uc?id=1B9R3dd3vgCdk6xf3vAl6tkPCcFTQHtvu&export=download&confirm=t)

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/45d7376b-1119-4630-9b92-6586c73e23e2)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/d945f806-4f9a-438b-80b8-22b15e989ab4)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/3ee9468f-0de9-432e-b2ed-0cf655503f23)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/af86bba1-04b4-4162-a9b9-7da85c2e1d75)

![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/1ac5a91d-9c5d-40a7-8e87-3dfc0638d6a0)

![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/a450ea21-2ef7-4dc7-a946-1df63552b5e6)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/ebf83389-412e-4580-a507-4e361291c3b8)
