### ISSUE TITLE
Lỗi - Không thu được tiền đối với bệnh nhân có tổng có phát sinh cùng chi trả (trường hợp đã thu 1 phần)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#174]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_ct_07032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_timmach_ct_07032024`](https://gofile.me/78TQg/VJUb7eJWd)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `24000002` - _**MaKB**_: `2403005726` - _**NgayKCB**_: `18/03/2024` - _**MaPhong**_: `01` - _**MaDV**_: `01` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Fees không thu được tiền bệnh nhân có phát sinh tiền cùng chi trả đối với trường hợp sau:
- Bệnh có toa thuốc thanh toán theo tỷ lệ 70 và lập phiếu thu. =>tổng phát sinh chưa vượt ngưỡng thu
-> sau đó chỉ định thêm toa thuốc mới => tổng phát sinh vượt ngưỡng thu.

==> lúc này Fees không thu được tiền bệnh nhân cùng chi trả.

```
Phiếu thu đầu tiên trước khi cho toa thuốc thứ 2
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/ab071b7f-ba70-4cbd-9c29-f6afa3f0925f)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/8e126b1e-7e16-4498-b642-bfd0c42b304e)

Sau khi cho toa thuốc có tổng phát sinh vượt ngưỡng
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/f4cfad28-270f-45db-8281-df9783c20eaa)
Fees không thu thêm được
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/37fca1e9-0790-41f9-9217-bcc70f68f309)

**Comment by gh-dh-bot-02** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại📣

**Comment by gh-dh-bot-02** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại📣

**Comment by ongtrieuhau** [comment]
Nhận nhé

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0611.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406110-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406110-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406110-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - Không thu được tiền đối với bệnh nhân có tổng có phát sinh cùng chi trả (trường hợp đã thu 1 phần)

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/174

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Fees vướng lại trường hợp chưa phát sinh cùng chi trả nhe anh @ongtrieuhau 

tổng tiền bh = 237,500 -> mà Fees có thu tiền cùng chi trả
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/043b9b60-3130-4134-91a3-e5153de08601)
bảng kê không có thu % CCT
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/783b5885-9cf2-4a2f-85b8-fd60d6c3a59b)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0612.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406120-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406120-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406120-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Không thu được tiền đối với bệnh nhân có tổng có phát sinh cùng chi trả (trường hợp đã thu 1 phần)

![](https://i.imgur.com/9X2ifVD.png)

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/174#issuecomment-2161981493

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Đã fix!
Đã thu được tiền cùng chi trả đối với cls đã thu chênh lệch dịch vụ.
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/2adb7d3c-726f-4c57-94e1-fcffaaae46c0)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/8e3ba619-9a02-4579-8f3b-4bfc4a3726a3)
