### ISSUE TITLE
Lỗi - Bảng kê tổng hợp theo dịch vụ, chi tiết theo dịch vụ, chi tiết theo bệnh nhân

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalfees#175]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_ct_02_032024_tonghoptheodichvu_20032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/8UG2zPQCq)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `03/03/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Lỗi khi bấm xem bảng kê tổng hợp theo dịch vụ, chi tiết theo dịch vụ, chi tiết theo bệnh nhân

Bị lỗi trong nhiều tháng, mỗi tháng bị lỗi 1 vài ngày không thống kê được dữ liệu
   Tháng 02/2023 không xem được ngày 10/02/2023, 16/02/2023, 23/02/2023,...
   Tháng 03/2023 không xem được ngày 03/03/2023,...
   Các tháng khác cũng bị lỗi

![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/b6342cf6-f610-4ba7-b369-00d2818b2181)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/31c650a7-f67d-4bdb-ada0-288f8b5bc2d6)

**Comment by gh-dh-bot-00** [comment]
<details> <summary>   ℹ️<code>2024-20-03 11:18:41</code> <code>@chauthanhtra</code><code>projects_v2_item.created</code>   <code>-NtP4I1fpug4YKC_15o8</code><code>GH</code> </summary> <code>[bot]</code><code>1.24.0319.1843@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1710907694021</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/8353690524'>webhook-logs</a>]</code></details>

**Comment by ongtrieuhau-dh** [comment]
Tiếp nhận

**Comment by ongtrieuhau-dh** [comment]
@chauthanhtra  kiểm tra lại dữ liệu giúp nhé, vào 2 ngày mà hổng thấy lỗi xuất hiện nhé 
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/155862740/6696ab8a-0950-48a9-bab4-03c997dd5fb2)


`Tháng 02/2023 không xem được ngày 10/02/2023`
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/155862740/32dc7a80-dca8-4731-9648-6e7e67745ff5)
`Tháng 03/2023 không xem được ngày 03/03/2023`
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/155862740/2a52c4b8-5ae2-4d8f-9494-12ee220404e0)

**Comment by chauthanhtra** [comment]
anh xem tháng 2, 3 năm 2023 nha anh. hình anh chụp năm 2024
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/12a71c22-8b48-439a-8b78-b0174daf0a66)

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupFees.v3.24.0326.1.msi](https://gofile.me/78TQg/Uyh1Kb68K)

**Comment by chauthanhtra** [comment]
Vẫn còn lỗi ở bảng kê chi tiết theo bệnh nhận và thêm lỗi chức năng kiểm tra dữ liệu ở bảng kê biên lai  tab tổng hợp CLS-DV

![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/d8070330-0034-4362-88d5-9ce131508f60)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/5b613c33-6bfc-4ced-a484-df359b614693)

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupFees.v3.24.0326.3.msi](https://gofile.me/78TQg/3K4SFuixE)

**Comment by chauthanhtra** [comment]
- Đã fix lỗi Xem Bảng kê chi phí tổng hợp và chức năng kiểm tra dữ liệu trong báo cáo biên lai

![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/ba942091-83a6-4e22-9386-cc76e3d053d6)

- Test bệnh nhân ngoại trú mới chưa phát hiện lỗi . Bảng kê, XML, thu phí bình thường

![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/5e6232bb-9546-4c9f-a3a9-8b5b7db094b0)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/bdcec821-1cda-408f-83e2-5434c1b96f73)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/0e56cdf6-2034-4577-a2e4-2d3dce9765c6)

- Test bệnh nhân nội trú mới chưa phát hiện lỗi . Tổng hợp thuốc, bảng kê, XML, thu phí bình thường.

![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/07356468-f7b1-4b4d-ba23-20b34266bd44)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/22508ec6-734a-4dbc-98ac-5204c27dc4e3)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/2200ca55-9c1b-443c-b05e-e942869d507a)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/97272332/1dbcb3e4-dc31-4b8f-af73-afb439586eb3)
