### ISSUE TITLE
Lỗi - Không hiển thị được danh sách phiếu thu do độ phân giải.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#177]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `24000247` - _**MaKB**_: `2403020380` - _**MaBA**_: `MaBA` _**NgayKCB**_: `27/03/2024` - _**MaPhong**_: `ALL` - _**MaDV**_: `ALL` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại bản mới cập nhật mã QR cho BV thì bị lỗi không hiển thị đầy đủ nội dung danh sách phiếu thu, bị che khuất như hình dưới, vì màn hình tại BV nhiều máy độ phân giải có độ cao phải lớn 768 mới thấy được, còn nếu độ phân giải có độ cao từ 768 trở xuống là cái khung phiếu thu bị khuất mất.

![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/36abcc7d-0621-4d35-a84b-eea43761ef3d)

Trước đây bản cũ thì không bị.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/77ea423d-0a3e-4178-91b9-022fdc75abeb)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalfees/177)

**Comment by ongtrieuhau** [comment]
Ok

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupFees.v3.24.0328.2.msi](https://gofile.me/78TQg/BHaBAYteX)

**Comment by lqbinh1987** [comment]
Đã fix.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/af50e9ba-a242-408e-918a-779098283217)
