### ISSUE TITLE
Lỗi - Không hiển thị trang in đã được thiết kế.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#179]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51214`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nội Tiết**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvnoitiet_042024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://dhsolutions.synology.me:5001/d/s/xwDVoLzBb8EwjLgk27ulEWEu3pKvhijL/4dg9dGbd4hUUX_DaMayfoMpiMDIJxKmy-JbigTb7LQgs)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `ALL` - _**MaKB**_: `ALL` - _**MaBA**_: `ALL` _**NgayKCB**_: `ALL` - _**MaPhong**_: `ALL` - _**MaDV**_: `ALL` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Phàn bảng kê Thanh toán không tiền mặt của Viettinbank.
Trang in đã thiết kế xong, lưu rồi, đóng form thiết kế lại, vào lại form thiết kế thì nội dung đã thiết kế không còn nữa. => Nhấn in thì cảnh báo là chưa thiết kế trang in.

![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/2d33b0bd-cde9-422b-8f09-a9c3e9544096)

Đã thiết kế và lưu rồi.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/c9cc8ffd-f5b3-41e4-afa1-1be26a44e142)

Nhưng vào lại thì như chưa thiết kế
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/5ec3f29d-451f-4ec8-9851-45fa0a3f7373)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalfees/179)

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [Fees.exe.v3.24.0515.0.msi](https://storage.googleapis.com/remmesionlangter-01.appspot.com/msiFiles/Fees.exe/Setup-Fees.exe.v3.24.0515.0.msi)

**Comment by hvtuan1987** [comment]
@ongtrieuhau Bản này vẫn chưa lưu mẫu tự thiết kế lại được anh Hậu. Khi load mẫu xong lưu lại và khi vào lại form thiết kế vẫn trống như cũ.

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau  xem lại chổ này dùm e, em test trên bản mới nhất cũng chưa được nhe anh.

**Comment by lqbinh1987** [comment]
Chưa lưu được trang in thiết kế.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0602.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406021-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406021-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406021-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Không hiển thị trang in đã được thiết kế.

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/179

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by ongtrieuhau-dh** [comment]
https://github.com/dh-hos/dhg.hospitalfees/assets/155862740/743a2647-1312-45e9-ac56-e980159626c3

**Comment by lqbinh1987** [comment]
Đã fix
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/fd31d7cc-7c98-4fa1-8331-2eafe81b4e36)
