### ISSUE TITLE
Lỗi - Quét mã QR không hiển thị thông tin điểm bán và số tài khoản.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#180]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_timmach_ct_qr`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `12114030` - _**MaKB**_: `2404019192` - _**MaBA**_: `MaBA` _**NgayKCB**_: `25/04/2024` - _**MaPhong**_: `NV` - _**MaDV**_: `01` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại lập phiếu thu xong, tại BV hiển thị mã QR ra màn hình rồi, nhưng khi quét mx QR thông tin không có tài khoản và tên thụ hưởng.

Mã phát sinh tại bv.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/18bea076-975f-43a1-81db-465f24b86394)

![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/62d7eab4-488d-4e0b-aab9-0348caf3dcc7)

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupFees.v3.24.0425.2](https://gofile.me/78TQg/5Kib4BiXW)

**Comment by lqbinh1987** [comment]
Đã fix.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/0d34ecdc-ae22-4092-89fa-34402e9a9acd)
