### ISSUE TITLE
Lỗi - Gen mã QR sai thông tin.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#181]
Thử

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalfees/181)

**Comment by ongtrieuhau-dh** [comment]
Cập nhật 
- [Fees.exe.v3.24.0515.0.msi](https://studentglendale-my.sharepoint.com/personal/cgoggan444_student_glendale_edu/_layouts/15/download.aspx?share=EVc3vbcg6shOk0LxSBZsxGgBLsB-M8i_gWXZ6aM2jTSOTg)
- [Fees.exe.v3.24.0515.0.msi](https://storage.googleapis.com/remmesionlangter-01.appspot.com/msiFiles/Fees.exe/Setup-Fees.exe.v3.24.0515.0.msi)

**Comment by lqbinh1987** [comment]
Bị lỗi khác anh @ongtrieuhau.
BN đang có chi phí viện phí và nhà thuốc:
Hiện tại bản mới này bị lỗi(Hình 1) khi nhấn nút làm tươi danh sách BN.
Chọn BN nhấn Thêm => Lưu lần 1 cũng bị văng ra lỗi trên(vẫn lưu được phiếu thu), đóng lỗi Lưu lần 2 thì báo lỗi(Hình 2), sau đó nhấn bỏ qua thì cũng báo lỗi cũ(Hình 1) tiếp, nhấn đóng lỗi tiếp..kết thúc thao tác => phiếu thu vẫn có, và không hiển thị thông tin QR ra màn hình phụ.
Thao tác trên là chỉ thu 1 loại chi phí hoặc của Nhà thuốc hoặc của Viện phí, nhưng khi chọn lại tên BN thì không còn chi phí gì để thu mặc dù là BN vãn còn chi phí để thu, nên chưa thể xác định được phiếu thu thứ 2 trở đi sinh mã QR đúng hay chưa?


Phiên bản :2024.05.15.024254AM
System.MissingMethodException: Method not found: 'Void OTH.PAY.ViettinBank.QRCode.ShowQR.ShowOnSecondScreenByQRPay(OTH.Entity.HosFees.QRPay, System.Collections.Generic.List`1<OTH.Entity.current.thuchi>, System.Collections.Generic.List`1<OTH.Entity.current.chidinhcls>, System.Collections.Generic.List`1<OTH.Entity.current.chungtu>, System.Collections.Generic.List`1<OTH.Entity.current.pshdxn>, System.String, System.Decimal, System.String, System.String)'.
   at HosFees.FormsV2.FrmCPhiBenhNhan.showQRToSecondScreen()
   at HosFees.FormsV2.FrmCPhiBenhNhan.<InitializeViettinBank>b__26_3(Object sender, EventArgs e)
   at Janus.Windows.GridEX.GridEX.OnSelectionChanged(EventArgs e)
   at Janus.Windows.GridEX.GridEX.ax()
   at Janus.Windows.GridEX.GridEX.set_Row(Int32 value)
   at Janus.Windows.GridEX.GridEX.m()
   at Janus.Windows.GridEX.GridEX.a(CurrencyManager )
   at Janus.Windows.GridEX.GridEX.a(Object , String , Boolean )
   at Janus.Windows.GridEX.GridEX.set_DataSource(Object value)
   at HosFees.FormsV2.FrmCPhiBenhNhan.click_BenhNhan()
   at HosFees.FormsV2.FrmCPhiBenhNhan.btnClick(Object sender, EventArgs e)

Hình 1:
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/7485dbfc-bbd3-4e52-a804-f1894b3872ef)

Hình 2:
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/ec715083-3ea6-4281-9bbc-8a56ff1a5702)

**Comment by gh-dh-bot-01** [comment]
Thử

**Comment by gh-dh-bot-01** [comment]
Thử

**Comment by gh-dh-bot-01** [comment]
Thử lần 2

**Comment by gh-dh-bot-01** [comment]
https://github.com/dh-hos/dhg.hospitalfees/issues/181

**Comment by gh-dh-bot-01** [comment]
https://github.com/dh-hos/dhg.hospitalfees/issues/181#issuecomment-2107195125

**Comment by gh-dh-bot-01** [comment]
3.24.0516.5 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405165-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405165-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405165-NasDHSolutions.json)

- 🐛: Lỗi - Gen mã QR sai thông tin

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/181

**Comment by gh-dh-bot-01** [comment]
### Cập nhật phiên bản Fees.exe v.3.24.0516.6 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405166-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405166-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405166-NasDHSolutions.json)

# Nội dung cập nhật

- 🐛: Lỗi - Gen mã QR sai thông tin

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/181

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Cập nhật Fees.exe v.3.24.0516.7 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405167-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405167-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405167-NasDHSolutions.json)

# Nội dung cập nhật

- 🐛: Lỗi - Gen mã QR sai thông tin

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/181

<div align="right"> 
  
          [![View](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe.exe?tab=readme-ov-file#readme)
        </div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0516.8 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405168-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405168-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405168-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Gen mã QR sai thông tin

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/181

<div align="right">

[![View](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0516.9 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405169-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405169-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405169-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - Gen mã QR sai thông tin

- 🐛: Fix Lỗi - System.MissingMethodException: Method not found: 'Void OTH.PAY.ViettinBank.QRCode.ShowQR.ShowOnSecondScreenByQRPay

![image](https://i.imgur.com/Z9DeYjy.png)

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/181

<div align="right">

[![View](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme)
</div>

**Comment by lqbinh1987** [comment]
Anh @ongtrieuha, đã gỡ bản cũ, xóa thư mục cài đặt và cài lại bản mới, nhưng vẫn còn lỗi
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/9a39dde8-3dcf-4ef9-8bff-2e8232d2a8e5)

**Comment by ongtrieuhau-dh** [comment]
Cho anh xin lại database nhé, nảy code lỡ xóa thông tin rồi @lqbinh1987

**Comment by lqbinh1987** [comment]
> Cho anh xin lại database nhé, nảy code lỡ xóa thông tin rồi @lqbinh1987

binh_loi_qr_2
này nhé anh @ongtrieuhau

**Comment by ongtrieuhau-dh** [comment]
Check lại cái nhé [Không thấy lỗi](https://i.imgur.com/b6nVhof.gif)

**Comment by lqbinh1987** [comment]
Theo như thao tác của anh không ra lỗi đâu anh @ongtrieuhau , anh phải thao tác làm tươi, hoặc lưu phiếu thu nó mới ra lỗi, rồi bỏ qua nó cũng mới ra lỗi.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/1c19c8f8-ff8f-4661-91b8-e1822804e5f9)
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/29e2e552-c521-4769-aab1-c19f1ea656d0)

**Comment by ongtrieuhau-dh** [comment]
@lqbinh1987 nhập 1 bệnh nhân để thử nhé

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau :
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `24008767` - _**MaKB**_: `2405006081` - _**MaBA**_: `MaBA` _**NgayKCB**_: `17/05/2024` - _**MaPhong**_: `31` - _**MaDV**_: `01` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_timmach_qr_loi`

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0517.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405170-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405170-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405170-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi lập phiếu thu khi có genQR, build lại để kiểm tra

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/181

<div align="right">

[![View](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![View](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-dh-informational?logo=github)](https://github.com/ongtrieuhau-dh)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0517.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405171-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405171-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405171-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi lập phiếu thu khi có genQR, build lại để kiểm tra

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/181

<div align="right">

[![View](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![View](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-dh-informational?logo=github)](https://github.com/ongtrieuhau-dh)
</div>

**Comment by lqbinh1987** [comment]
Đã fix.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/02baccec-f9cd-4d77-acf5-dd06f8ef099b)
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/d1e4988c-17ae-4be9-8048-d7e4c866697d)
