### ISSUE TITLE
Lỗi - Nút thu tạm ứng bị lỗi.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#182]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_timmach_qr_loi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `22019808` - _**MaKB**_: `MaKB` - _**MaBA**_: `24001856` _**NgayKCB**_: `ALL` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `17` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi click vô nút Tạm ứng thì báo lỗi như hình 1, sau khi đóng lỗi vẫn vô được form, nhấn chọn phiếu thu thì khung bên phải không load dữ liệu theo phiếu thu đó như hình 2.

Nhờ anh @ongtrieuhau tranh thủ phần nầy vì nếu trả về bản cũ thì lỗi gen QR lộn tài khoản của BV.

Hình 1:
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/627305c4-882b-4d1d-b32d-1598b1dff787)

Hình 2:
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/4615329d-5a73-4381-bcc1-e1f10691002f)

**Comment by ongtrieuhau-dh** [comment]
Để kiểm tra nhé

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0517.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405172-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405172-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405172-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi khi chọn [Tạm ứng] ![image](https://i.imgur.com/309zyyK.png)

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/182

<div align="right">

[![View](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![View](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh)
</div>

**Comment by lqbinh1987** [comment]
Đã fix
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/700d9f99-47ae-4ff6-868c-a3d0948ea32a)
