### ISSUE TITLE
Lỗi - MẤT KÝ TỰ % LÝ DO THU KHI LẬP HOÁ ĐƠN TỔNG

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalfees#183]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92120`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN ĐA KHOA TÂM MINH ĐỨC**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_tmdct_sailydothu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018074237` - _**MaKB**_: `2405014193` - _**MaBA**_: `MaBA` _**NgayKCB**_: `24/05/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Lý do thu % BHYT khi lập phiếu thu thì có ký tự "%" nhưng khi vào chức năng lập hoá đơn tổng theo BN thì mất ký hiệu "%" còn lại thì không thay đổi.
Đơn vị báo kiểm toán không chịu nên nhờ anh check dùm em sớm.

![image](https://github.com/dh-hos/dhg.hospitalfees/assets/130281806/f0b89c8c-b9ff-43e6-98b2-f4452d8ed3fa)
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/130281806/3606a899-35b8-4b68-81ed-032156101e21)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalfees/183)

**Comment by nghivanbi** [comment]
@ongtrieuhau fix gấp lỗi này cho bênh viện nhé.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0527.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405270-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405270-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32405270-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi mất % lý do thu

- 🐛: Fix xuống dòng địa chỉ trên phiếu thu

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/171

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/183

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
Chưa được nhe anh @ongtrieuhau, lúc mới vào form tại BN đó thôi thì nó load đúng(Hình 1), nhưng sau khi **Lưu** thì nó bị mất ký tự % (Hình 2)
Trong form theo menu **Hóa đơn điện tử/Đồng bộ hóa đơn cuối ngày - Theo bệnh nhân** cũng bị tình trạng vậy.
Hình 1:
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/85189ca6-6ed5-4ab2-ae44-23aeb7c5718e)

Hình 2:
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/0d5e51c7-2e1b-4102-a6c4-27604aa82766)

**Comment by ongtrieuhau-dh** [comment]
Ok, để check lại nhé

**Comment by ongtrieuhau-dh** [comment]
Backup dữ liệu ra link cái nhé

**Comment by hvtuan1987** [comment]
@ongtrieuhau Links dữ liệu Full á: https://drive.google.com/file/d/1SRoZ_bojQcOp0TYme1gW80JIvD1h3dhV/view?usp=sharing

**Comment by nghivanbi** [comment]
@lqbinh1987 này ok chưa?

**Comment by lqbinh1987** [comment]
Đã fix, hỗ trợ V vào ngày 28/05 rồi.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/7a4da30b-3dd3-4c1f-8bbb-b7f4ea53998e)
