### ISSUE TITLE
Lỗi - Nội dung thu bị trùng khi lập HDDT.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#184]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92120`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Minh Đức CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_tmdct_sailydothu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1KuXeKviVGMq9eJ8QCSiTixkwG7gt2zDN/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2405014194` - _**MaBA**_: `MaBA` _**NgayKCB**_: `24/05/2024` - _**MaPhong**_: `A1` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trường hợp BN có 2 phiếu thu: phiếu thu chi phí đồng chi trả BHYT và phiếu thu chi phí ngoài BHYT, có lập phiếu thu tổng theo BN, sau đó lập HĐĐT cho phiếu thu tổng đó, thì trong xml đẩy lên cổng HĐĐT ghi nhận nội dung đang gom lý do thu của 2 phiếu thu vào chung luôn, và hiển thị 2 dòng giống nhau(hình 1), nhưng số tiền của mỗi dòng vẫn đúng, tổng tiền cũng đúng.
Trước kia đúng là mỗi dòng là lý do thu riêng của từng phiếu thu như Hình 2.
Đoạn xml ghi nhận: 
[xml.txt](https://github.com/user-attachments/files/15513306/xml.txt)

Hình 1:
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/60f4e827-e1bb-4a08-a590-de980df15615)

Hình 2:
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/ea5b6dba-5015-4c64-ba64-6d9f5ca48918)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalfees/184)

**Comment by lqbinh1987** [comment]
Check dùm em cái này anh @ongtrieuhau.
Chiều đang làm tắt máy chác nó dính phím nên nó lưu lun.

**Comment by ongtrieuhau-dh** [comment]
Cái này phải cấu hình lên cái cổng demo cái, mới thử được, chứ thiệt là toi á

**Comment by ongtrieuhau-dh** [comment]
Cấu hình xong cho hay nhé

**Comment by lqbinh1987** [comment]
Này em có cấu hình sai cổng ws của nó. Lúc lập hddt nó có báo lỗi anh. Trong lỗi cũng có đoạn xml mình gửi đi.

**Comment by lqbinh1987** [comment]
Chứ nó hổng có lập hddr thiệt được

**Comment by ongtrieuhau-dh** [comment]
Ok

**Comment by lqbinh1987** [comment]
Coi giúp em chổ nỳ lun nhe anh Hậu

**Comment by ongtrieuhau-dh** [comment]
Dữ liệu lấy về hổng thấy cái phiếu thu đó

**Comment by ongtrieuhau-dh** [comment]
![](https://i.imgur.com/hikxZPu.png)
Kiểm tra lại cái @lqbinh1987 , sao debug hổng thấy như vậy

**Comment by ongtrieuhau-dh** [comment]
Bản mới nhất vẫn không thấy bị ![](https://i.imgur.com/ZBbp0ih.png)

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau.
Rồi e mới test kỹ lại, để xảy ra lỗi trên thì anh phải lập phiếu thu tổng ở form **Lập hóa đơn tổng theo bệnh nhân(menu: Hóa đơn điện tử/Đồng bộ hóa đơn cuối ngày - Theo bệnh nhân -  Hình 1)** , rồi sau đó anh lập hóa đơn điện tử tại form nào cũng bị lỗi.
Ngược lại nếu anh lập phiếu thu tổng tại(form thu tiền BN, nút Lập hóa đơn điện tử xổ ra, chọn lập hóa đơn tổng hợp theo bệnh nhân - Hình 2) thì anh lập hddt cho phiếu thu tổng đó ở form nào cũng sẽ đúng.

Hình 1:
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/a5c501d6-edd2-48f2-9013-eed0f1911a51)

Hình 2:
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/185ee314-be49-4823-a191-7e044632265f)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0602.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406020-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406020-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406020-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Nội dung thu bị trùng khi lập HDDT. (menu: Hóa đơn điện tử/Đồng bộ hóa đơn cuối ngày - Theo bệnh nhân)

- 🐛: Lỗi - Nút bỏ qua không có tác dụng

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/184

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
Đã fix, nối dung xml đã tách được 2 dòng riêng biệt.
Nút bỏ qua cũng xài được.
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/b75ce14d-2f65-4e5c-a14f-4a580f8b2746)
