### ISSUE TITLE
Lỗi - Check trạng thái thanh toán giao dịch QR nhà thuốc.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#186]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51214`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nội Tiết**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_ttntqn_checkttthanhtoan_nhathuoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1QcjtuCNYZz6KDMQutmsdmjpe0jfyixTz/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018004230` - _**MaKB**_: `2406000243` - _**MaBA**_: `MaBA` _**NgayKCB**_: `03/06/2024` - _**MaPhong**_: `03` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)
BN thanh toán bằng mã QR, tiền vào tài khoản của BV, thông tin merchant là **success**, dh01 có, nhưng dữ liệu không cập nhật được vào cho BV, check log tại BV thì ko thấy đoạn insert vào bảng exchanges.

File log: 
[dh-service-qrcode-vietin_20240603.out.log](https://github.com/user-attachments/files/15544920/dh-service-qrcode-vietin_20240603.out.log)

![image](https://github.com/dh-hos/dhg.hospitalfees/assets/99630883/2543967e-4e41-4f7a-aa6c-6df0c905f9b9)

**Comment by ongtrieuhau-dh** [comment]
Tiếp nhận nhé, nhưng đang ưu tiên 4750, nên tạm thời xử lý theo hướng dẫn trước nhé, nếu gặp nhiều hơn thì xử lý theo gấp hé @lqbinh1987

**Comment by lqbinh1987** [comment]
Ok anh
