### ISSUE TITLE
Lỗi - Fees Bảng kê biên lai thu không tách được chi phí nhà thuốc sang cột (Chi phí nhà thuốc)

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalfees#187]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77120`,`77127`,`77150`,
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **3 cơ sở PKĐK Medic Sài Gòn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_medicsg_tachthuocdv`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/pTW8NreR5)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024004066` - _**MaKB**_: `2406002241` - _**MaBA**_: `MaBA` _**NgayKCB**_: `20/06/2024` - _**MaPhong**_: `22` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**MaHH**_: `MaHH` - _**SoHD**_: `PHU.00461/202406` - _**NgayHD**_: `20/06/2024` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)

Khi thu chung cận lâm sàng và thuốc trên cùng 1 phiếu thu  phần tiền không hiển thị  sang cột Chi phí nhà thuốc như hình dưới
Fees: Báo cáo-> Bảng kê biên lại thu không tách được phần tiền thuốc sang cột Chi phí nhà thuốc như hình dưới
Form phiếu thu
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/97272364/80683080-abfb-4fda-b4ae-c27d886d1172)

Form Báo cáo
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/97272364/5aa4ffed-890e-403f-861c-46a769e1a8b3)

**Comment by ongtrieuhau-dh** [comment]
Cái này thu chung thì không tách được, phải riêng bằng nút [Thuốc NT] mới tách riêng theo bảng kê biên lai nhé

**Comment by hvtuan1987** [comment]
Mấy đơn vị này là bên mình làm đặc thù á ! Thu chung tự tách ! Để em kiếm bản cũ của đơn vị gởi hình á

**Comment by hvtuan1987** [comment]
@ongtrieuhau Fees cũ 3.23.0412.2  lúc thu cls + thuốc anh có ghi nhận cột thucthu_dichvunt của tiền thuốc nên Báo cáo-Biên lai thu tách được á
Bản Fees mới không có ghi nhận nên không tách 
Em cài lại Fees cũ 3.23.0412.2 xóa và thu lại thì đúng á !
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/97272364/4af7d828-6deb-4350-83cf-cf7926016dc0)

**Comment by hvtuan1987** [comment]
@ongtrieuhau Nào rảnh coi lại dùm em á !

**Comment by ongtrieuhau-dh** [comment]
[Xem vấn đề tại đây nhé](https://github.com/dh-hos/To_Lap_Trinh/issues/332)
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/155862740/c1cd385e-6332-4416-b365-b63cb65c4080)

**Comment by hvtuan1987** [comment]
Em cấu hình lại được rồi á !
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/97272364/a7910333-23a7-4514-a784-43f5bcf13ee4)
