### ISSUE TITLE
Lỗi - Fees tính sai tiền cung chi trả đối với bệnh nhân đã có phiếu thu (BV Tâm Phúc)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#188]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `60152`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Phúc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamphuc_fees_cct_26062024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_tamphuc_fees_cct_26062024`](https://gofile.me/78TQg/u1wK3LwdY)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024022586` - _**MaKB**_: `2406006774` - _**NgayKCB**_: `25/06/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân ngoại trú đã lập 2 phiếu thu trước không có phát sinh cùng chi trả.
-> Cập nhật Fees 18/06 báo có phát sinh cùng chi trả

```
> Phiếu thu 1
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/55590bba-029f-45f5-8489-2f636472eeaf)
> Phiếu thu 2
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/56629ca7-7b48-4ff4-9dc8-066e0baa38a8)
> Fees thu tiền cùng chi trả
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/0d0c1fb6-c172-4e56-bb0e-297edaeabbd2)
***
> Khi xóa hết 2 phiếu thu thu lại thì không có tiền cùng chi trả
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/e55f1947-28cf-4ec2-aa37-7ce3298a5896)

**Comment by ongtrieuhau-dh** [comment]
Để code check nhé

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0626.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406260-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406260-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32406260-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Fees tính sai tiền cung chi trả đối với bệnh nhân đã có phiếu thu (BV Tâm Phúc)

![](https://i.imgur.com/SotusD3.png)

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/188

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/e3f82931-3fbf-4690-bec9-ab7e1fc99422)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/397af9dc-437a-4ad3-b312-77ffb390ebc4)
![ảnh](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/66746c23-1434-4aef-97bf-0bfe26aa2c9e)
