### ISSUE TITLE
Fees tính sai cùng chi trả đối với bệnh nhân có sử dụng sten và có chứng nhận miễn cùng chi trả

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#19]
Dữ liệu: an_dktpct_treatfees
Bệnh nhân có chứng nhận miễn từ ngày 14/4/2022
và có sten 1 ngày 13/4
sten ngày ngày 21/4 thanh toán 50%
Fees tính cùng chi trả ở sten 2 và miễn ở sten 1.
![image](https://user-images.githubusercontent.com/96155021/166645238-e77682ff-db81-418e-baab-b6848ad22adb.png)
tiền cùng chi trả ở Fees
![image](https://user-images.githubusercontent.com/96155021/166645371-3bb8d58c-7003-4373-a363-3d8b682bbf39.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Hiện tại đang thực hiện theo mô tả này. 
[Vinh - Mo ta thuc hien vat tu stent thu 2 - 27-08-2019 - v4.docx](https://github.com/oth-dhghospital/dhg.hospitalfees/files/8674491/Vinh.-.Mo.ta.thuc.hien.vat.tu.stent.thu.2.-.27-08-2019.-.v4.docx)

**Comment by le-an-87** [comment]
cái mô tả em coi không thấy có mô tả trường hợp chứng nhận miễn đó anh.
trường hợp bệnh nhân này có nhập chứng nhận miễn cùng chi trả thì những chi phí từ ngày miễn giảm được miễn cùng chi trả anh ơi

**Comment by nghibi** [comment]
Hậu cập nhật cách tính theo mo tả này
[Vinh.-.Mo.ta.thuc.hien.vat.tu.stent.thu.2_Bi_cap_nhat_20220517.pdf](https://github.com/oth-dhghospital/dhg.hospitalfees/files/8705066/Vinh.-.Mo.ta.thuc.hien.vat.tu.stent.thu.2_Bi_cap_nhat_20220517.pdf)
:

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật theo mô tả mới tại đây https://github.com/oth-dhghospital/dhg.hospitalfees/commit/f39c42ee4766672c92540067ad50e5a5437d2b60

**Comment by le-an-87** [comment]
Fees mới em test lại cũng chưa được anh @o-ngtrieuhau861gmailcom ơi!
em thử chừa lại 4 cái stent thì Fees tính ra như hình sau
em lấy tiền 20% của bệnh nhân tính lại thành tiền thì 3,600,000 * 100/20= 18,000,000
số tiền này mới bằng giá bhyt của stent 2 hà anh ơi!
![image](https://user-images.githubusercontent.com/96155021/169495870-c7cb9815-af13-4777-9b5f-257a18eb025c.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Theo cách tính mới này 
![image](https://user-images.githubusercontent.com/58720300/169925723-00a2ef48-6c2d-4eec-868d-22dd2f28fddb.png)
thì chỉ có mức hướng thay đổi, nhưng với thông tin bệnh nhân hiện tại thì MUC_HUONG đã bằng 100 rồi, nên khi áp dụng vào nó vẫn vậy, không có thay đổi.

**Comment by le-an-87** [comment]
chổ hình em chụp đó anh bệnh nhân có stent 1 không được miễn giảm giá thanh BHYT là 36,000,000 đ -> bnctt (20%) = 36,000,000 x 20 /100 = 7,200,000 mà Fees tính ra có 3,000,000

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại https://github.com/dh-hos/dhg.hospitalfees/commit/a07fb07bd678786b3a63f5a8a77258b86af64119

**Comment by le-an-87** [comment]
đã kiểm tra khớp sô tiền với Treatment!
