### ISSUE TITLE
Lỗi - Lập hóa đơn điện tử toa bán lẽ báo lỗi (BV Lấp Vò)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#190]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87005`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Lấp Vò**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_hddt_07082024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_lapvo_hddt_07082024`](https://gofile.me/78TQg/m7FaxexAu)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `BLNT3.00001/0824` - _**MaKB**_: `BLNT3.00001/0824` - _**NgayKCB**_: `01/08/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**SoHD**_: `NT3.00001/0824` - _**NgayHD**_: `01/08/2024` - _**ThangKT**_: `08` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chứng từ bán lẻ khi thu tiền xong -> lập hóa đơn điện tử báo lỗi.

```
![ảnh](https://github.com/user-attachments/assets/33e282c3-7f68-4f29-8e33-6b2fe89d2914)
![ảnh](https://github.com/user-attachments/assets/02cb3988-e644-4dff-8215-95a26ff64632)

![ảnh](https://github.com/user-attachments/assets/fb59a17e-2bb9-4115-8b8c-963c328994c1)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-12**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ❌ **Từ chối tiếp nhận** 
- 📣 **Nguyên nhân**: _**KHÔNG TÌM THẤY BỆNH NHÂN BỊ LỖI**_
![](https://i.imgur.com/oGjHu5L.png)

[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.] Nghĩa vụ: ghi nhận vi phạm nếu có tại HD.04, phản hồi
đủ thông tin

**Comment by le-an-87** [comment]
anh @ongtrieuhau kiểm tra lại giùm nhe!
![ảnh](https://github.com/user-attachments/assets/6c02a140-c6fc-4514-a1cc-8811211d0695)

**Comment by ongtrieuhau-dh** [comment]
📣 Đã thấy thông tin, do thiếu chỗ này
![](https://i.imgur.com/7A4O5yB.png)

**Comment by ongtrieuhau-dh** [comment]
### 📢 @le-an-87  liên hệ với bệnh viện và cổng HDDT để xử 
Chỗ này có thể cổng nó đang chặn do làm tròn số (hiện có 2 hướng xử lý)

1. Điều chỉnh số làm tròn bằng option để gửi cổng ![](https://i.imgur.com/RnaDN3P.png)
2. Nếu **_bước 1_** không được, thì liên hệ với chỗ hỗ trợ HDDT xem hướng xử lý trường hợp này thế nào, vì làm tròn chắc sẽ không khớp được. Nếu muốn khớp cổng, thì sẽ không khớp với số tiền ở Fees.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Issuse không có sản phẩm để kiểm tra.
✔️Đã hướng dẫn khách hàng xử trí hóa đơn
***
