### ISSUE TITLE
Lỗi - BC bảng kê chi tiết theo bệnh nhân (BV Tim Mạch AG)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#191]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_baocaovienphi_09082024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_timmach_baocaovienphi_09082024`](https://gofile.me/78TQg/dZo12anVp)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022029462` - _**MaKB**_: `2408006896` - _**MaBA**_: `MaBA` _**NgayKCB**_: `08/08/2024 8:20:38 SA` - _**MaPhong**_: `PK01` - _**MaDV**_: `01` - _**ThangKT**_: `08` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
bệnh nhân có 2 phiếu thu:
- 1 phiếu thu tại Fees
- 1 phiếu lập tại printer
-> báo cáo Bảng kê chi tiết theo bệnh nhân bị double số biên lại

```
![ảnh](https://github.com/user-attachments/assets/3f72f6e4-1e17-4750-a782-b30e6963b129)
![ảnh](https://github.com/user-attachments/assets/2bc976dc-9a80-4ea8-b398-74a6fb73b1f5)
![ảnh](https://github.com/user-attachments/assets/74d58c19-c6a9-4bc6-bba2-fe2de910cb37)
![ảnh](https://github.com/user-attachments/assets/b7332274-2fcd-483e-8a3f-1b9d560ee965)
![ảnh](https://github.com/user-attachments/assets/c408a335-f022-4aa0-be5c-2838d9c8df20)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-15**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @le-an-87 
- 👉: _**Chạy scriptFix**_
![](https://i.imgur.com/cUzkK9y.png)
- 📙: Nhờ @le-an-87 kiểm thử thêm nguyên nhân gây trùng dữ liệu
![](https://i.imgur.com/TjiXy1c.png)

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ TEST**
***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:

- Hình ảnh lỗi:


> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/fbbf0901-f94f-498d-9cb8-519cf8ba38ad)
![ảnh](https://github.com/user-attachments/assets/46bea900-aee2-48da-9015-5e783de54905)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu: đã hỗ trợ xử lý lỗi bệnh nhân đã báo.
***
- Tiến hành hỗ trợ khách hàng.
