### ISSUE TITLE
Yêu cầu - Kiểm tra thông tin QR gửi cho Bank 

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#193]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Huyện Phước Long BLI**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbphuoclong_bli_qr`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/xdbEDaSBO)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện tại khi gen QR test luồng thanh toán thành công thì bank trả về tại trang https://dh01-mabv-95006-default-rtdb.asia-southeast1.firebasedatabase.app/.json là:
{"amount":"9860","bankTransactionId":"4GI2Y-7tdOn5Hmj","merchantId":"1900345506","merchantName":"TTYT Phuoc Long",**"orderId":"1031130"**,"productId":"","requestId":"15255","signature":"nwkL8u29PBDQMy1Sf/TJk0KMqcDLcs1ZECDwK5CAQXEd120dCGiJiq+WKy5IsC4m3JRIOgjzo9h9ZUJJcYdQGTgv+pmu6bcT5Hcv/E8gpW/fWW6wLzeuBTxU0s6/HJhuAJ2JnvWsBLGHITsN+Ofv+WrG4mbHDnVGJtMWofunlKe4zgiC13u6f328QkktFoU/xco+0GmkQknx0lO9zmw7cYKyM/Fp5YSMWdHuQPokiBnoamgEBBiAeWy1AOpfzW4SQ8Q8OTI6jL5pkOD/h8iBhtDXyfqNtUZrQrmbJyFkksfAli4KX7xqatBDzvIMyrNhqhMqahZx7tJCGr+l4giTXw==","statusCode":"00","statusMessage":"Tru tien thanh cong, so trace 15255,TTQR-1031130-000015255-HOANG NGOC HAI-VietinBank-********3786","terminalId":"122000123936","transactionDate":"20240822131743"}

Trong khi đó trong thuchi.pay_qrid lại có giá trị khác so với bank trả về.
Do không có ghi log dữ liệu gửi cho bank nên e không xác định được, nhờ a Hậu hỗ trợ check dùm em.

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-28**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by lqbinh1987** [comment]
Tranh thủ chổ này dùm em nhe anh, vì đang test luồng thanh toán để đưa vào hoạt động chính chức.

**Comment by ongtrieuhau-dh** [comment]
#### 📢 @lqbinh1987 

- **_Nhờ phía bank kiểm tra lại thử xem, hình như bên đó trả dữ liệu bên mình bị sai rồi_**, ![](https://i.imgur.com/0ueyenI.png) ![](https://i.imgur.com/kBjdi2t.png)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0823.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408230-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408230-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408230-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: **💼**: **_Yêu cầu - Kiểm tra thông tin QR gửi cho Bank _**

- ✨: Fix lỗi thiếu billNumber khi tạo QR

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/193

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0824.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408240-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408240-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408240-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: **💼**: **_Yêu cầu - Kiểm tra thông tin QR gửi cho Bank _**

- ✨: Fix lỗi thiếu billNumber khi tạo QR khi in phiếu thu

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/193

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0824.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408241-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408241-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408241-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: **💼**: **_Yêu cầu - Kiểm tra thông tin QR gửi cho Bank _**

- ✨: **💼**: **_Yêu cầu - FEES - Triển khai thanh toán mã QR MOMO_**

- ✨: Fix lỗi thiếu billNumber khi tạo QR khi in phiếu thu, tích hợp Momo, VietQR

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/193

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/416

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
Đã hỗ trợ
![image](https://github.com/user-attachments/assets/205d3bda-093a-418b-b36e-005d61a39bf3)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0825.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408250-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408250-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32408250-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Bổ sung trang thể hiện mã QR tự thiết kế (đăng nhập tài khoản admin sẽ hỏi trang thiết kế) đối với mã khách hàng không thuộc mẫu mặc định đã thiết kế riêng (**_92001,51214,70071,95006,92118_**)

![](https://i.imgur.com/13A5cXo.png)

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/193

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/416

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>
