### ISSUE TITLE
Lỗi - Fees tính sai số tiền Còn nợ khi bệnh nhân thu chi phí nội bộ

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalfees#194]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_fees_dathunoibo_pmbaoconno_10092024_1`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/5Uunplrpt)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024071790` - _**MaKB**_: `2409002252` - _**MaBA**_: `015050` _**NgayKCB**_: `5/9/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `07` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân đã lập phiếu thu nội bộ chi phí nhưng phần mềm báo bệnh nhân còn nợ chi phí (đã lập phiếu thu nội bộ nhưng số tiền còn nợ không đổi)

![ảnh](https://github.com/user-attachments/assets/3f622fd8-62d9-4f8c-9629-143b5f5855d3)
![ảnh](https://github.com/user-attachments/assets/5f37322f-f1d2-412a-b833-9f04f2592eb7)
![ảnh](https://github.com/user-attachments/assets/3924d3d4-7db6-4fe1-ba5f-b79d52d42676)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-16**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### 📢 @chauthanhtra 

- Hỗ trợ bằng cách cập nhật script
- Nội dung script cập nhật 
```
UPDATE current.thuchi
SET thucthuct = thucthu
WHERE soct = 'C33..00531/09'
  AND mabn = '2024071790'
  AND makb = '015050';
UPDATE current.congno
SET 
    psno = 691800,
    thu = 691800,
    nock = -8305147
WHERE mabn = '2024071790' AND maba = '015050';
```

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Cập nhật script
***
>Lỗi, yêu cầu đã hoàn thành 

- Nội dung: 

  - Sau khi cập nhật script thì hết lỗi bệnh nhân này

- Hình ảnh: 

![ảnh](https://github.com/user-attachments/assets/f2273197-c45d-4cf2-8d3f-d38ff4e6ef89)


***
 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

- Diễn giải lỗi:

  - Test Phần mềm Fees ngày 11/09 vẫn còn lỗi. 
  - Xóa hết chi phí thu lại thì vẫn sai cần phải fix lại phần mềm
  - Phiếu thu nội bộ không có thucthuct , congno cũng ghi nhận sai

- Hình ảnh lỗi:

![ảnh](https://github.com/user-attachments/assets/3fafceb5-f3d1-4af1-bda0-a9d02698aa64)
![ảnh](https://github.com/user-attachments/assets/11160465-cc3a-4fc0-a2c1-88a1869d9279)
![ảnh](https://github.com/user-attachments/assets/32f5898b-9a9f-4328-b7bb-ed3a2213d1b0)


> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

Mà chổ này phần mềm Fees đang thu sai anh có fix phần mềm Fees chưa anh?

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại phần mềm Fees

**Comment by ongtrieuhau-dh** [comment]
Lý do là phần công nợ đã nằm trong phần tạm ứng rồi.

**Comment by chauthanhtra** [comment]
Em chưa hiểu chổ này lắm
Theo hình em gửi ở dưới thì số tiền còn nợ đâu có đúng 
![ảnh](https://github.com/user-attachments/assets/a2902434-15af-4a1e-9dc5-9d694f23df0e)

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @chauthanhtra  </sub>

1. ***Thu thêm***: **Đây là số tiền bệnh nhân cần phải đóng thêm. Dữ liệu trên không có giá trị, tại vì khi nào không có tiền tạm ứng, hoặc tiền tạm ứng không đủ đối với phiếu thu đó thì mới có giá trị**. Ví dụ giải thích tiền thu thêm: Lập phiếu thu 100,000

- Nếu Tạm ứng >= 100,000 => Thu thêm  0
- Nếu Tạm ứng = 50,000 => Thu thêm: 50,000

2. Tính lại số tiền còn nợ sẽ đúng theo qui tắc cấn trừ tạm ứng trên

**Comment by chauthanhtra** [comment]
### **Hoàn Thành**

- Code đã giải thích do BV thu phí sai qui trình, BV phải lập tạm ứng hết chi phí trước khi lập phiếu thu. Code đã có họp với BV về qui trình thu phí và cách thể hiện chi phí nhưng chưa thống nhất được với BV
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
