### ISSUE TITLE
Yêu cầu - Bổ sung loại chi phí Không chịu thuế lên HĐĐT-Viettel

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#195]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả khách hàng sử dụng HĐĐT Viettel`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả khách hàng sử dụng HĐĐT Viettel**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_pkphucgiakhang_hddt_082024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/qzOCi58pn)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện tại đối với 1 số phòng khám thì chi phí liên quan đến khám chữa bệnh thì thuế có quy định là loại chi phí **không chịu thuế**, thể hiện lên hóa đơn điện tử là dạng ký tự \ như hình.
![image](https://github.com/user-attachments/assets/f75879c2-6f82-49e8-9cc7-2569ac77df3b)

Mà hiện tại trên phần mềm chỉ cho cấu hình thuế bắt buộc phải là số, để 0% thì cũng không đúng quy định không chịu thuế.
Nên e đề nghị cả 2 tab viện phí và nhà thuốc bổ sung Check và ô text nhập nội dung khi áp dụng, khi chọn check thì đẩy giá trị vào taxPercentage trong json truyền lên cổng hđđt,  nếu không chọn check thì áp dụng mức thuế theo cấu hịnh hiện tại đang có.
![image](https://github.com/user-attachments/assets/1e590e1c-3915-42f2-8b01-ec6cf1379c69)

**Comment by lqbinh1987** [comment]
Anh @nghivanbi xem xét giúp em

**Comment by nghivanbi** [comment]
### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @ongtrieuhau
⌛ **Hạn hoàn thành mong muốn**:
📘 **Nội dung**: Hỗ trợ các đơn vị xuất hóa đơn không chịu thuế.

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-23**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Fees.exe v.3.24.0918.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32409181-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32409181-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FFeesexe%2F32409181-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: **💼**: **_Yêu cầu - Bổ sung loại chi phí Không chịu thuế lên HĐĐT-Viettel_**

- ✨: Thêm chức năng cấu hình thuế suất với giá trị tùy chọn ![](https://i.imgur.com/B19dIVh.png)![](https://i.imgur.com/O6l0psK.png)

- ☑: https://github.com/dh-hos/dhg.hospitalfees/issues/195

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Fees.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
✅ **Đã hỗ trợ**
![image](https://github.com/user-attachments/assets/89c09bd4-3827-4258-a1ac-a66949717f47)
