### ISSUE TITLE
Lỗi - Fees hiển thị tiền tạm ứng sai chi phí bệnh nhân nội trú

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalfees#198]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Đa Khoa TPCT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbtpct_sai_tongthu`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Kp1cE5g4w)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024060552` - _**MaKB**_: `2409006114` - _**MaBA**_: `029280` _**NgayKCB**_: `13/09/2024 ` - _**MaPhong**_: `105` - _**MaDV**_: `22` - _**ThangKT**_: `09` - _**NamKT**_: `2024`

Bệnh nhân nội trú có lập phiếu thu tổng tiền khớp nhưng Fees vẫn còn báo nợ:

  **Tổng chi phí bệnh nhân: 109.946.477**
 **Bệnh nhân tạm ứng: 56.000.000**
**Thực thu % BHYT+ Dịch vụ: 35.134.233**
**Hoàn ứng: 20.865.775**
### Nếu so chi phí thì số tiền thực thu bệnh nhân 35.134.233 là đang đúng 

Em có test thử khi xóa phiếu thu và phiếu tạm ứng cũ và lập lại phiếu thu và phiếu tạm ứng mới thì thu lại bình thường.
Nhưng khi bấm vào nút Thêm trên Fees thì hiển thị thêm số tiền: 33,173,365 (Số tiền đang báo bệnh nhân nợ nhưng thực tế không còn nợ ).

Hình Tổng chi phí tại Treatment
![image](https://github.com/user-attachments/assets/8839bb4e-8c86-4e4c-a857-baab72e6782e)
Hình tại module Fees khi đã lập phiếu thu trước đó
![image](https://github.com/user-attachments/assets/36c8f18f-a42e-4b85-910b-fad7af3c6ca6)
Hình tại module Fees khi bấm vào Nút Thêm
![image](https://github.com/user-attachments/assets/8c10d22d-1c07-46ab-a115-7d202a0d90ee)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-25**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @hvtuan1987 
- **Chạy script này để hỗ trợ khách hàng**: `UPDATE current.pshdxn SET soctvp='ƯEW..00402/09' WHERE mabn='2024060552' AND makh='029280' AND COALESCE(soctvp,'')='' AND COALESCE(xoa,0)=0 AND kyhieu<>'TMO';`
- Đề nghị restore lại dữ liệu để chạy thử, dữ liệu trên server hiện tại thử đã không như phía bệnh viện.
- ![](https://i.imgur.com/QcRRWxE.png)

**Comment by hvtuan1987** [comment]
## 📣 @ongtrieuhau 
Xác nhận sau khi chạy Script đã lấy đúng chi phí !
