### ISSUE TITLE
Lỗi DLL - Hậu check lại 

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalfees#34]
![image](https://user-images.githubusercontent.com/91751241/172093832-04194dd8-2f6d-48a3-a227-94fdd5b9346c.png)
Report đang gọi theo hàm này:
![image](https://user-images.githubusercontent.com/91751241/172093887-a354929b-a219-49da-b1f8-44944b71f684.png)
Phiên bản đang sd:
![image](https://user-images.githubusercontent.com/91751241/172093918-0f8458c7-8c30-4446-8184-063cca9d056c.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Add thêm dll này vào sẽ hết lỗi XtraRPT.old.dll
![image](https://user-images.githubusercontent.com/58720300/172105708-0dd7da63-2c96-498e-9f7b-71167ccc871d.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cái này xong chưa @nghibi

**Comment by nghivanbi** [comment]
OK
