### ISSUE TITLE
Tạm ứng - lỗi không bắt được số tồn biên lai.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#35]
Đã thu hết số biên lai tạm ứng nhưng không có cảnh báo hoặc chặn hết số biên lai.
Data: dbnhidong05, quyển tạm ứng 157

![image](https://user-images.githubusercontent.com/99630883/172112421-fb473c6c-38f2-46bd-9478-dc6a448c7558.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
- Cập nhật tại https://github.com/oth-dhghospital/dhg.hospitalfees/commit/81975b5beda024cddc41fae59827df3eddde2021
- 
![image](https://user-images.githubusercontent.com/58720300/173738153-1cce14a7-6636-4ef4-ad08-d6fb240085b2.png)
