### ISSUE TITLE
Bổ sung lý do xóa HDDT-VAT

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#38]
Khi xóa hóa đơn yêu cầu phải có lý do xóa cụ thể.
Mô tả theo như tài liệu của bên Kha cung cấp, mục 3.3.19 và 3.3.21.
Link tài liệu: https://docs.google.com/document/d/13Gmw2ADtprZ9SG3gl0dMd_yCAfENnmrA1MmMcgsUxVo/edit.
Data test: binh_nhidong, phiếu thu như hình 
![image](https://user-images.githubusercontent.com/99630883/173261034-40852c34-fac7-43c5-a712-3504c256bee1.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cái này để bàn lại với bên VAT xem bên đó có hỗ trợ được hông
