### ISSUE TITLE
Fees lỗi tính sai chi phí khi cấu hình CN.Miễn trên Treatment 

### ISSUE THREAD

**Issue by BlueTea92** [dh-hos/dhg.hospitalfees#41]
BV Tim Mạch CT
- Fees tính sai chi phí bệnh nhân khi bệnh nhân có chứng nhận miễn có ngày bắt đầu miễn trên Treatment 
![ảnh](https://user-images.githubusercontent.com/97272332/174212142-c8d10fce-ebb3-4242-9d0d-4bf951a78c80.png)
- Khi xóa ngày bắt đầu miễn trên bnnoitru.ngaymienct thì Fees tính đúng lại số tiền
+ khi chưa xóa bnnoitru.ngaymienct
![ảnh](https://user-images.githubusercontent.com/97272332/174207049-144ccad7-a315-4c02-8a35-cb4d0ac3e081.png)
+ khi đã xóabnnoitru.ngaymienct
![ảnh](https://user-images.githubusercontent.com/97272332/174207148-ca0d6349-2f97-466a-aaa5-224aef852b6f.png)

- Data máy chủ: tra_timmachct_fees_treat
- Mabn: 22012760
- Tên: Lê Hồng Cúc

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại https://github.com/dh-hos/dhg.hospitalfees/commit/a07fb07bd678786b3a63f5a8a77258b86af64119

**Comment by BlueTea92** [comment]
ok anh @o-ngtrieuhau861gmailcom
