### ISSUE TITLE
Fees_Bảng kê bệnh nhân nợ viện phí_Load sai chi phí phát sinh

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalfees#42]
Data: duc_tracu
Tổng chi phí hay Tổng PS của BN trên Thu phí Nội trú là: 2.516.012 >>>> Trên Bảng kê nợ viện phí cột Phát sinh thực tế chỉ có 1.916.522
![image](https://user-images.githubusercontent.com/98437757/174212686-f7961483-f4b8-4903-89b4-e1fe32654433.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại https://github.com/dh-hos/dhg.hospitalfees/commit/3378ca1f5f57c576d2d85071119b7765319af49d
