### ISSUE TITLE
Lỗi nút Lập và in hóa đơn điện tử.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#43]
Nút Lập và in hóa đơn điện tử bấm vào không có tác dụng

![image](https://user-images.githubusercontent.com/99630883/174215715-9b878f2e-09be-46b1-bb6f-d91ac173e443.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Không thấy thông tin dữ liệu để fix lỗi. Kiểm tra lại nhé @lqbinh1987

**Comment by lqbinh1987** [comment]
Data này nhe anh: binh_nhidong_full
![image](https://user-images.githubusercontent.com/99630883/174734879-b865189f-0ac8-4e87-9791-0e84d69d1cfb.png)

**Comment by ongtrieuhau** [comment]
Chuyển qua đúng module để thực hiện nhé
