### ISSUE TITLE
Bổ sung thêm số tài khoản khi lập HDDT-VNPT

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#46]
Hiện tại nhật ký khi lập HDDT của VNPT e không thấy mình đẩy số tài khoản lên, nhờ a Hậu đẩy thêm số tài khoản vào thẻ dùm. Form thu tiền ngoại trú/nội trú/tự do.

Data: binh_tamnong, maba: 2022002041

![image](https://user-images.githubusercontent.com/99630883/174697404-e88af90f-3c8a-4e1f-9156-9d3870cae921.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại https://github.com/dh-hos/dhg.hospitalfees/commit/b6a7c974694bf4052e4108fee4c8bd06b69f1e46

**Comment by lqbinh1987** [comment]
> Hiện tại nhật ký khi lập HDDT của VNPT e không thấy mình đẩy số tài khoản lên, nhờ a Hậu đẩy thêm số tài khoản vào thẻ dùm. Form thu tiền ngoại trú/nội trú/tự do.
> 
> Data: binh_tamnong, maba: 2022002041
> 
> ![image](https://user-images.githubusercontent.com/99630883/174697404-e88af90f-3c8a-4e1f-9156-9d3870cae921.png)

**Comment by lqbinh1987** [comment]
Nhờ a Hậu truyền lại vào thẻ "CusBankNo" dùm e. Do hổm tên thẻ nó nằm trong dấu <> nên nó hổng hiển thị mà e hổng để ý.

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0629.2](https://github.com/dh-hos/dhg.hospitalfees/commit/27837e66924c847d449844e8e6069eedd7075987)
