### ISSUE TITLE
Thu tự do bổ sung thêm 1 số nội dung.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#47]
Bổ sung thêm chổ thu tự do cho nhập đầy đủ **Đơn vị tính, đơn giá, số lượng, thành tiền.**
để khi lập hóa đơn điện tử lên đúng như người dùng nhập.

Data: binh_nhidong_full

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0629.3](https://github.com/dh-hos/dhg.hospitalfees/commit/f2f37e3c8460f9faeb65482bb0c859efdce7d164)
