### ISSUE TITLE
Yều cầu: Triển khai kết nối hóa đơn điện tử (70002-TTYT HUYỆN HỚN QUẢN)

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalfees#48]
- Kết nối: Viettel.

**Comment by ongtrieuhau** [comment]
{"AtRow":61,"mabvbh":"70002","DateExpires":"2022-08-01","UseHddtBy":"Viettel","Trial":""}
=====DECODE=====
U2FsdGVkX180upZOHHKixzaFU5xJoRtmKf8QYBUMk2Atg4bim297HWfQ3t47fa5h15T9jLbY/n3l8whRyOZTifHyu4ftpXWUAPe8z4aaeqt4gtmTD3vEi0kIlPYYZPNG8JVH2IyNbHjwAEr4VMdzUg==
