### ISSUE TITLE
BV Tim Mạch CT-Sai mẫu kết toán viện phí bệnh nhân có stent 2

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalfees#49]
BV Tim Mạch CT
1. Bệnh nhân có stent 2 đã thu hết chi phí nhưng bảng kết toán viện phí vẫn ghi nhận bệnh nhân còn nợ.
2. Không đủ chổ trống ghi nhận số tiền trên bảng kết toán viện phí nên hiển thị số tiền ########
3. Bảng kê bệnh nhân nợ viện phí cũng hiển thị bệnh nhân còn nợ

![ảnh](https://user-images.githubusercontent.com/97272332/175243957-66be2176-32c1-4e40-834a-28b3dfb888e5.png)
![ảnh](https://user-images.githubusercontent.com/97272332/175244037-e2337e2b-d428-4305-85aa-fd913cb05e7f.png)
![ảnh](https://user-images.githubusercontent.com/97272332/175261077-7a667f7c-b7d8-446a-84fc-808622e7dc25.png)

Data máy chủ: tra_timmachct_cnmien_new
MABN: 22009542
MABA: 2022001106
Tháng KT: 05/2022
Data drive: https://drive.google.com/file/d/1Sjyg4XqQurde_eYjyHJ8wIIHH3RPhoNe/view?usp=sharing

**Comment by ongtrieuhau** [comment]
Cập nhật tại [v3.22.0629.1](https://github.com/dh-hos/dhg.hospitalfees/commit/16f895d79e4dbec27b43d83cbf6d9a13bb340149)

**Comment by chauthanhtra** [comment]
ok anh @ongtrieuhau
