### ISSUE TITLE
Lỗi - Fees lập HDDT cho nhà thuốc. Tiêu chí bảng kê biên lai.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#51]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Nhi Đồng CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_nhidong_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh%2001-Fees_lập_HDDT_cho_nhà_thuốc.-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `2206027754` - _**MaBA**_: `MaBA` _**NgayKCB**_: `16/06/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `06` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: Số chứng từ viện phí `J6.00007/06`, có sử dụng tham số **_vpnhathuoc_khocp_**

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. Khi cấu hình máy có check **Viện phí nhà thuốc**, nhưng khi lập hddt thì phiếu thu đó trong thuchi.nhathuoc **không ghi nhận được là 1**.(Hình 1)

Hình 1.

![image](https://user-images.githubusercontent.com/99630883/175850333-945bcd37-ba09-400f-ab3a-b4cc9489a9c1.png)
###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh%2002-Lỗi_tiêu_chí_Bảng_kê_thu_chi-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `` - _**MaBA**_: `MaBA` _**NgayKCB**_: `16/06/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `06` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: Có sử dụng tham số **_vpnhathuoc_khocp_**

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. Như trong hình, menu Báo cáo/Biên lai/Bảng kê biên lai thu, thì tài khoản vvquoc thu của nhà thuốc(Hình 2). Nhưng trog Menu Bảng kê/Tổng hợp/Bảng kê thu chi, Tab Tổng hợp thu chi: Khi check Chỉ Viện phí nhưng nó vẫn load dữ liệu luôn của nhà thuốc và ngược lại khi chọn Chỉ nhà thuốc nhưng vẫn load dữ liệu của viện phí.(Hình 3)

Hình 2.
![image](https://user-images.githubusercontent.com/99630883/175850985-14637cb6-889a-4088-bfb5-2054aac2bcf0.png)

Hình 3.
![image](https://user-images.githubusercontent.com/99630883/175851208-888d9205-16d4-42bf-b609-1873063bb865.png)

**Comment by ongtrieuhau** [comment]
![image](https://user-images.githubusercontent.com/58720300/176398672-074cab14-38f3-4933-af31-0ae6397a0fcd.png)

Hiện tại chức năng này hông có hỗ trợ đối với mabvbh = 92003,  (Đây là danh sách các bv có thể sử dụng chức năng này: `92004|92017|87005|92013|79029|92118|92127|92015|87014|87179`)

**Comment by ongtrieuhau** [comment]
![image](https://user-images.githubusercontent.com/58720300/176400204-7df7318f-54b2-4678-87c0-45d277ac84db.png)
Đây là bảng kê sử dụng như chức năng nộp tiền cho người thu, nên không phân biệt nhà thuốc hay viện phí. Nếu xem theo tiêu chí này là lấy tất cả dữ liệu, vì nó có cần trừ giữa thu giữa phiếu thu, tạm ứng và phiếu chi nữa, nên không thể tách riêng theo tiêu chí nhà thuốc.

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0707.1](https://github.com/dh-hos/dhg.hospitalfees/commit/c1b1cd8aa7e43c18894a94074a4ec0fe5c95b0b1)
