### ISSUE TITLE
Yêu cầu - Thay đổi tên trường lý do xóa HDDT Viettel

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#52]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **ngay_tiep_nhan**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87011`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TRUNG TÂM Y TẾ HUYỆN LAI VUNG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `dblaivung2020027123_2204003687_n2022001068`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện tại khi phần mềm mình xóa HDDT thì có cho nhập nội dung và truyền vào "additionalReferenceDesc" ok rồi, nhưng giờ bên VT thay đổi tên trường truyền vào là **reasonDelete**, nhờ a Hậu thay đổi dùm.
Cụ thể tài liệu: Mục 7.6 - Hủy Hóa đơn. 
[tl_mo_ta_webservice_hoadondientu_doitac_v2.5_public.docx](https://github.com/dh-hos/dhg.hospitalfees/files/8988486/tl_mo_ta_webservice_hoadondientu_doitac_v2.5_public.docx)

Data: dblaivung2020027123_2204003687_n2022001068.
Mã BANT có phiếu thu: N2022001068

![image](https://user-images.githubusercontent.com/99630883/175854031-373380aa-e979-4a16-a2d6-6317c981f128.png)

**Comment by ongtrieuhau** [comment]
Cập nhật tại [v3.22.0629.5](https://github.com/dh-hos/dhg.hospitalfees/commit/94ab78b1b48381412bef9c02c365fc115f72bba3)
