### ISSUE TITLE
Lỗi - Fees load chi phí nhà thuốc

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#54]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Nhi Đồng CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_nhidong_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh%2001-Fees_load_chi_phí_nhà_thuốc.-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `2206000089` - _**MaBA**_: `MaBA` _**NgayKCB**_: `01/06/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `06` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `A49.00004/202206` - _**NgayHD**_: `01/06/2022` - _**ThangKT**_: `06` - _**NamKT**_: `2022`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: Có sử dụng tham số **_vpnhathuoc_khocp=|02|03|_**

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. Cấu hình máy không có check **Viện phí nhà thuốc**, nhưng vẫn load chi phí của nhà thuốc thuộc kho 13 lên.(Hình 1)

Hình 1.
![image](https://user-images.githubusercontent.com/99630883/177920435-c12f47e8-a4d0-45ce-aa41-79cd17e8f115.png)

**Comment by ongtrieuhau** [comment]
Trong Menu Bảng kê/Tổng hợp/Bảng kê thu chi, Tab Tổng hợp thu chi: Không tách được báo cáo của viện phí và nhà thuốc mặc dù đã check chọn.(Hình 2)=> Không thực hiện vì phần trước đã nói rồi, mục đích là để nộp tiền thì phải nộp chung hết, đâu có tách ra được

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0708.1](https://github.com/dh-hos/dhg.hospitalfees/commit/1896f0117cd2d97887f0eb3c25a743c3e1935320)
