### ISSUE TITLE
Yêu cầu - Đề nghị cập nhật tham số phieuthubnchuaxv

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#55]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/7/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_yhct_79_xml`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Tham số: phieuthubnchuaxv
Diễn giải:
Cho phép lập phiếu thu đối với bệnh nhân chưa xuất viện trong nội trú và bệnh án ngoại trú (   
0: Không áp dụng 
1: Áp dụng và chỉ lấy chi phí trong nội trú tới ngày làm việc  
2: Áp dụng và lấy toàn bộ chi phí theo bệnh nhân  )

khi sử dụng phieuthubnchuaxv = 0
FEES sẽ không thu tiền đối với đối tượng BHYT nhưng sẽ cho thu đối tượng THU PHÍ

*Đề nghị:
 - Cập nhật lại diễn giải nếu tham số chỉ áp dụng cho đối tượng bhyt!
 - Nếu áp dụng cho tất cả đối tượng -> Fees bắt bổ sung thêm đối tượng thu phí!

```
đối tượng thu phí thu được
![image](https://user-images.githubusercontent.com/96155021/179152256-8eccef73-9ec4-4f9d-9863-ebfc79519d55.png)

đối tượng bhyt không cho lập phiếu thu
![image](https://user-images.githubusercontent.com/96155021/179152323-a6c529ff-36fe-4c09-a6a3-e3fee57ebd4a.png)

*Hiện tại thêm tìm theo mã bệnh nhân/ bệnh án và nhấn nút Thêm thì Fees sẽ cho thu được tiền của đối tượng bhyt!
![image](https://user-images.githubusercontent.com/96155021/179152389-2d87e1ed-836d-4a63-b3c9-de02b83f566d.png)
![image](https://user-images.githubusercontent.com/96155021/179152407-9c926063-f977-4357-9435-cf8c1dd827bf.png)

**Comment by ongtrieuhau** [comment]
- Phần thay đổi diễn giải tham số sẽ cập nhật lại. (tham số này chỉ áp dụng cho đối tượng thuộc diện BHYT, Thu phí thì muốn thu lúc nào cũng được) 
- Phần thêm được phiếu thu đối với bệnh nhân BHYT khi chưa xuất viện thì không tìm thấy mã số bệnh án như hình. Đề nghị cung cấp lại chính xác thông tin lỗi.

**Comment by le-an-87** [comment]
em gửi lại tên data và mã bệnh án em test nhe!
tên data: an_test_xml
maba: N2022000002 - mabn: 2022000003 - thangkt: 05 - namkt: 2022

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0720.1](https://github.com/dh-hos/dhg.hospitalfees/commit/af62145c68c17f494c58c9601b555635ca890d16)

**Comment by le-an-87** [comment]
Đã fix lỗi và cập nhật diễn giải tham số phieuthubnchuaxv!
