### ISSUE TITLE
Fees tính sai chi phí từ stent 2 trở đi khi bệnh nhân có check miễn cùng chi trả

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalfees#56]
Bệnh nhân sử dụng 2 stent  thứ 2 Fees tính sai chi phí ! Không tính đc tiền của stent2 khi cho số lượng từ sten2 từ 2 trở lên khi có check bệnh nhân miễn cùng chi trả !
Dữ liệu dktpcantho

**Comment by ongtrieuhau** [comment]
Bỏ cái này đi @hvtuan1987 , khi tạo cái mới thì close cái cũ để dễ theo dõi
