### ISSUE TITLE
Lỗi - Bảng kê load dữ liệu của xuất bán lẻ kho BHYT qua tiêu chí Nhà Thuốc.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#57]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `89015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch AG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbtimmach_072022`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `02` - _**MaHH**_: `MaHH` - _**SoHD**_: `D56.00001/0722` - _**NgayHD**_: `19/07/2022` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BV sử dụng chức năng xuất bán lẻ của kho BHYT ngoại trú, thu tiền ở viên phí(Không check Viện phí nhà thuốc ở cấu hình máy), nhưng khi thu tiền thì trong bản **thuchi.thucthu_dichvunt** vẫn ghi nhận số tiền, nên một số báo cáo khi check Nhà thuốc nó vẫn lấy lên dữ liệu.
 - Báo cáo/Biên lai/bảng kê biên lai thu.
 - Bảng ngoại trú | nội trú | tổng hợp / Bảng kê thu chi.

![image](https://user-images.githubusercontent.com/99630883/179665680-69957572-61a8-480e-9eee-d6c473673bc4.png)
![image](https://user-images.githubusercontent.com/99630883/179665526-6160591d-5719-4e02-82ae-332f91d6ec4b.png)
![image](https://user-images.githubusercontent.com/99630883/179665586-2f6b3df0-6e73-4d09-93a6-3fee80a93cd6.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0719.1](https://github.com/dh-hos/dhg.hospitalfees/commit/ad1d48271976cb994db470c7a4a251503f33d6fd)
