### ISSUE TITLE
Lỗi - Chỉnh phiếu thu chênh lệch

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#68]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92127`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Hòa Hảo CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_hoahao_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022057827` - _**MaKB**_: `2207013849` - _**MaBA**_: `MaBA` _**NgayKCB**_: `16/08/2022` - _**MaPhong**_: `30B` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Phiếu thu tiền chênh lệch(tiền DV trừ tiền BHYT), đã có phát sinh số chứng từ trong **chidinhcls.soctvp** và **chidinhcls.soctvpcl**, sau đó mở khóa phiếu thu ra, thao tác chỉnh phiếu thu lưu lại, thì **chidinhcls.soctvpcl** bị set lại giá trị rỗng, lúc này chưa phát sinh %BHYT, sau đó chỉ định thêm CLS hoặc tra toa thuốc thì tổng tiền vượt ngưỡng BHYT, dẫn đền tình trạng printer bắt lại vì chưa đóng tiền, nhưng nhìn trên fees đã có phiếu thu rồi, không còn chi phí để thu.
 
![image](https://user-images.githubusercontent.com/99630883/184797771-1f0aa78d-c4e6-4364-994d-251a424b38ed.png)
![image](https://user-images.githubusercontent.com/99630883/184797785-a411a4e7-ba2a-4607-aa78-faf8476f0f18.png)

**Comment by lqbinh1987** [comment]
Thực hiện theo quy chế và nội quy mới ngày 25/08/2022.

**Comment by lqbinh1987** [comment]
Nhờ anh @ongtrieuhau fix lỗi này dùm.

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0929.2](https://github.com/dh-hos/dhg.hospitalfees/commit/b26107fd43526f925a5e052e75e6dd9d75bfcf7a)
