### ISSUE TITLE
Lỗi - Lệch số tiền phiếu thu và số tiền chi tiết phiếu thu

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalfees#69]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20ghi%20nhận-:-blue?style=plastic&logo=github) **31/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN CHUYÊN KHOA SẢN - NHI ST**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_sannhist_lechphieuthuvscanthu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1YigGKdsbVmlCq2YgnsYHUkVVHQOevaaW/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022042094` - _**MaKB**_: `2208004317` - _**MaBA**_: `2022014233` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `KD045` - _**ThangKT**_: `08` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Số tiền trên phiếu thu và số tiền chi tiết các chi phí của phiếu thu bị lệch nhau

![ảnh](https://user-images.githubusercontent.com/97272332/187575323-16c98a0e-1320-4238-b8a3-933061fa73fd.png)

- Nguyên nhân là do chọn từng CLS để thu tách ra nhiều phiếu thu mà không thu tất cả cho phí trong 1 lần thu
-> các CLS cùng mã không được chọn vẫn bị ghi nhận đã thu có số chứng từ thu nhưng không được cộng số tiền vào phiếu thu

![ảnh](https://user-images.githubusercontent.com/97272332/187576094-d4521984-da51-460a-b7d2-0850b5f3e92b.png)
![ảnh](https://user-images.githubusercontent.com/97272332/187576146-f0d0a084-b85e-44ac-b1e8-62688f6a1513.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0929.3](https://github.com/dh-hos/dhg.hospitalfees/commit/c599be609c8b9251a9f21cea11bb8b3314196725)
