### ISSUE TITLE
Lỗi - Quét mã bệnh nhân thu tiền tự động khi phiếu thu in ra không có thông tin thu tiền - BV Tâm Phúc

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#72]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `60152`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK TÂM PHÚC**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamphuc_duocquocgia`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [``](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022044016` - _**MaKB**_: `2208002978` - _**NgayKCB**_: `07/09/2022` - _**MaPhong**_: `13` - _**10**_: `MaDV` - _**ThangKT**_: `08` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi sử dụng chức năng quét mã bệnh nhân lập phiếu thu tự động khi in phiếu thì không có thông tin phiếu thu.

```
Tham số cấu hình quét mã và in phiếu thu tự động
![image](https://user-images.githubusercontent.com/96155021/188778391-2c9485e8-ecc5-4f94-92a7-ad6bb77d348d.png)
Quét mã tự động thu tiền và in phiếu thu / (Form thu tiền không lấy được thông tin của phiếu thu vừa lập)
![image](https://user-images.githubusercontent.com/96155021/188778712-99ff45ae-dbf8-4ff8-be54-4cd0b6133bec.png)
Phiếu thu in ra bị trống số chứng từ và không có thông tin thu tiền
![image](https://user-images.githubusercontent.com/96155021/188778873-6476bfd2-eab3-43ec-880a-c94d8f98e36b.png)
Phiếu thu in lại
![image](https://user-images.githubusercontent.com/96155021/188778970-0a403f58-7356-4c79-9f7f-45de90e10ca0.png)

**Comment by ongtrieuhau** [comment]
Lấy bản mới nhất thử lại giúp nhé @le-an-87 , tại test bằng bản mới nhất lại hổng thấy tình trạng đó.  [Video](https://youtu.be/dRV7owkcuHk)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0929.7](https://github.com/dh-hos/dhg.hospitalfees/commit/1ea8191bee0671c2476fe296e8ca2a9dedfc6548)

**Comment by le-an-87** [comment]
đã fix!
