### ISSUE TITLE
Yêu cầu - Thực hiện kết nối HDDT BV Thới Lai (92009) - VNPT

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalfees#73]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92009`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thới Lai**
###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Hoàn thành trước 09/09/2022

```

**Comment by ongtrieuhau** [comment]
Cập nhật code nhé @lqbinh1987 
{"AtRow":62,"mabvbh":"92009","DateExpires":"2022-11-30","UseHddtBy":"Vnpt","Trial":""}
=====DECODE=====
U2FsdGVkX18mpQG/XISvfq7Jniiuq2JN1lYpAcuM/PCrTINhxY9y0qQHs1WTR2WWQs/4x0A9O6KVps21btArPOSiHOFTB3XS9aNTM3S//o6FacNBKv4ziImPnyj8TK+KBdlTL4AW08P6xm+SfYuksQ==
