### ISSUE TITLE
Lỗi - Fees load chi phí bệnh nhân khác khi tìm kiếm và chọn tên bệnh nhân trên danh sách

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalfees#75]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51009`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TT Y TẾ HUYỆN MỘ ĐỨC**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_moduc_092022_fees_loadsaichiphi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1_CJnPJCUnlKxMjRPMrucCvqOZF-8agG-/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `09` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Form thu phí khi tìm bệnh nhân và click chuột lần đầu vào bệnh nhân trên danh sách ở 1 số bệnh nhân (thường là bệnh nhân đầu tiên trên danh sách) thì sẽ load chi phí của bệnh nhân khác -> nhấp chuột lần 2 vào tên bệnh nhân mới load đúng chi phí
![ảnh](https://user-images.githubusercontent.com/97272332/189863740-1225b105-7b1f-42c0-bf12-325f11847356.png)
![ảnh](https://user-images.githubusercontent.com/97272332/189863816-46ab698e-59af-4805-aa48-2f9686cf9af0.png)

**Comment by ongtrieuhau** [comment]
Chỗ này đang thiết kế theo luồng thế này. Chuỗi tìm kiếm thay đổi, sẽ tự động lọc tên bệnh nhân trên lưới danh sách. Khi tìm kiếm kết thúc phải click vào bệnh nhân hoặc nhấn ENTER thì mới load thông tin và chi phí của bệnh nhân đang chọn trên lưới.
### Trường hợp click lần đầu vào lưới bệnh nhân mà không load lại thông tin và danh sách thì test không thấy tình trạng này nhé.
Kiểm tra lại chỗ này nhé @chauthanhtra [Video test thực hiện](https://youtu.be/AaGozIvFLcU)

**Comment by chauthanhtra** [comment]
Như clip anh gửi thì số tiền đúng của bệnh nhân Huấn này là 2,904,172 mới đúng anh số tiền 454,210 là của bệnh nhân Huy
![ảnh](https://user-images.githubusercontent.com/97272332/192983250-982a179b-9513-4f65-93f8-94ebc15396db.png)
![ảnh](https://user-images.githubusercontent.com/97272332/192983208-e7cf0749-0683-4fa7-b35b-893c8d7c141e.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0929.6](https://github.com/dh-hos/dhg.hospitalfees/commit/bddff6ac04c4348bc307181dc4fb374ebee1ab44)
