### ISSUE TITLE
Lỗi - Thu tiền bệnh nhân nội trú bị âm -1 đ

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#77]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/27/2022 16:27**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_omon_amtien_fees`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020028086` - _**MaKB**_: `2209006121` - _**MaBA**_: `2022011272` _**NgayKCB**_: `16/09/2022` - _**MaPhong**_: `P7` - _**MaDV**_: `07` - _**ThangKT**_: `09` - _**NamKT**_: `2020`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Fees thu tiền bệnh nhân nội trú bị âm -1đ

```
![image](https://user-images.githubusercontent.com/96155021/190606198-7edce5c2-b875-4e23-aef1-5d2cdfb2ce25.png)

![image](https://user-images.githubusercontent.com/96155021/190606085-3f6f9d1a-03eb-4f9e-9976-fb89bdd2acee.png)

**Comment by ongtrieuhau** [comment]
Check lại bản mới nhất nhé @le-an-87 . Hổng thấy tình trạng này xảy ra.
![image](https://user-images.githubusercontent.com/58720300/192971906-bb16e99b-6e92-48ab-b7a3-324389a6a23a.png)

**Comment by le-an-87** [comment]
Kiểm tra bản mới không bị lỗi!
