### ISSUE TITLE
Lỗi - Phiếu thu đã lập bị mất thông tin khi lập BANT.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#78]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92127`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Hòa Hảo CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_hoahao_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022057832` - _**MaKB**_: `2207013858` - _**MaBA**_: `N2022000802` _**NgayKCB**_: `22/09/2022` - _**MaPhong**_: `29B` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi BN đăng ký xong**(chưa vào phòng khám)**, sau đó qua thu tiền chênh lệch công khám, phiếu thu in ra bth:
![image](https://user-images.githubusercontent.com/99630883/191653215-4e0fb234-e4e2-4c54-b472-c7a6084f9ac9.png)

Thu tiền chênh lệch ck xong BN vào phòng khám, BS lập BANT **(có check BA YHCT - theo đợt)**.
Lúc này phiếu thu ban đầu trong menu **Phiếu thu\Ngoại trú**, không còn thấy chi tiết cls đã thu nữa:
![image](https://user-images.githubusercontent.com/99630883/191652628-f6ec45df-424b-4d9a-9843-fed45d5220a4.png)

Bấm in lại cũng không thấy thành tiền.
![image](https://user-images.githubusercontent.com/99630883/191652802-add03cc6-ea29-408c-9de3-4573692b587a.png)

**Comment by ongtrieuhau** [comment]
Phần này, kiểm tra lại có chuyển phiếu thu này theo vào bệnh án chưa nhé @lqbinh1987 .

**Comment by lqbinh1987** [comment]
Không nhe anh @ongtrieuhau, thuchi.makh vẫn là ID khám bệnh của ngoại trú.
Hiện tại e tìm cũng không thấy tham số hay option nào chuyển phiếu thu vào BANT.

**Comment by ongtrieuhau** [comment]
Đúng thì lúc lập bệnh án phải chuyển phiếu thu này vào bệnh án chứ.

**Comment by ongtrieuhau** [comment]
> Hiện tại e tìm cũng không thấy tham số hay option nào chuyển phiếu thu vào BANT.
 Cái này xem chỗ lập bệnh án xem thế nào nhé. Còn hông thì liên hệ với @nghivanbi nhé

**Comment by lqbinh1987** [comment]
Trường hợp này sao hé anh @nghivanbi ?

**Comment by nghivanbi** [comment]
if (objBNNoiTru.bnnoitru.Psdangky["bant"] + "" == "0")//chuyển tạm ứng khi là bệnh án thanh toán đợt
                                {
                                    DLLFees.ChuyenCPhiTamUng.ChuyenVao(objBNNoiTru.bnnoitru.Mabn, objBNNoiTru.bnnoitru.Makb, objBNNoiTru.bnnoitru.Maba, FrmMain.strUserName, FrmMain.strTenMay, FrmMain.strThangKT, FrmMain.strNamKT);
                                }

**Comment by ongtrieuhau** [comment]
Đây là chi phí đã thu nên phải chuyển bằng hàm này chứ **DLLFees.CPhiDaThu.ChuyenVao**, chuyển bằng thằng này DLLFees.ChuyenCPhiTamUng.ChuyenVao là chuyển tạm ứng thôi. Nhờ @nghivanbi  kiểm tra lại
