### ISSUE TITLE
Lỗi - Chức năng xóa và in lại trang in HDDT của VAT

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#79]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92017`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Da Liễu CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `dbdalieu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022034953` - _**MaKB**_: `2207012134` - _**MaBA**_: `MaBA` _**NgayKCB**_: `28/07/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Đã sử dụng chức năng xóa trang in hddt và in lại nhưng vẫn không có thông tin tên nhân viên chuyển đổi.
**Lưu ý dữ liệu đang cấu hình hóa đơn điện tử chính thức.**
![image](https://user-images.githubusercontent.com/99630883/191912110-c89d9020-8c20-4d29-9b93-f734925b5e88.png)
![image](https://user-images.githubusercontent.com/99630883/191918517-c0f6db5f-ce8d-4d40-9f51-91b6a5c066fd.png)

**Comment by ongtrieuhau** [comment]
Cái này liên hệ lại với cổng nhé, vì chức năng xóa mới thêm này chỉ hỗ trợ xóa những dữ liệu đã tải về trước đó. Khi in sẽ thực hiện download trực tiếp trên api cổng trả về. Hiện tại test thử là lấy mới về từ trên cổng vẫn hổng có tên người chuyển đổi như hình nhé. 
![image](https://user-images.githubusercontent.com/58720300/192974663-f724367d-a09f-4fb5-be06-fd6bff3bb52b.png)
Lưu ý: code hiện tại download trang in này, hông có truyền user thì lên cổng hết nhé.
