### ISSUE TITLE
Yêu cầu - Chọn quyển khi lập Tạm ứng/Hoàn ứng.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#80]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/09/2002**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị ST**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_malk__`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu bổ sung option bắt buộc chọn quyển khi lập tạm ứng hoặc hoàn ứng, vì có trường hợp máy này đang lập tạm ứng, có chọn quyển, thì số biên lai của quyển tạm ứng đó nhảy liên tục, nhưng khi máy khác thu tạm ứng, thì nó không tự động nhảy quyển tạm ứng, kế toán không để ý thì lúc này tại máy đó lập tạm ứng hàng loạt không có thông tin quyển tạm ứng.(BV đang xài tham số  **Số chứng từ nội bộ của phiếu Tạm ứng và Hoàn ứng =0: Tăng theo tên máy**.
![image](https://user-images.githubusercontent.com/99630883/192213167-6f4eb738-d1bf-4a4f-8031-56f171ee4ebc.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0929.5](https://github.com/dh-hos/dhg.hospitalfees/commit/5dc08dd57d9d276c0877aaab9906aef9d85fd119)
