### ISSUE TITLE
Lỗi - Lệch tiền phiếu thu

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#81]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87115`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phổi ĐT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phoi_dt_saitien_phieuthu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022005936` - _**MaKB**_: `2208001628` - _**MaBA**_: `2022002073` _**NgayKCB**_: `06/09/2022` -  _**MaDV**_: `06` - _**ThangKT**_: `09` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Tiền thực thu và tiền bệnh nhân trả của phiếu thu nội trú bị lệch!
số tiền trên lý do thu: Thu phí(XN:2,000) + 20.00%BHYT (CN:32,800; Thuốc&VTYT:3,121,589; GB:3,742,000; XQKTS:130,800; CCT:522,000; XN:806,500)
cộng các khoản lại đều khớp so với tổng tiền form thu phí.

Bệnh viện nhờ kiểm tra nguyên nhân gây lệch tiền!

```
![image](https://user-images.githubusercontent.com/96155021/193966226-dd8a1f24-d628-43a2-ac30-4d7ec0cb6803.png)

**Comment by ongtrieuhau** [comment]
Không tìm thấy dữ liệu an_phoi_dt_saitien_phieuthu trên máy chủ.

**Comment by le-an-87** [comment]
em trao đổi với bệnh viện được rồi anh ơi! có thể do bệnh viện chỉnh dữ liệu. anh khỏi kiểm tra vụ này nữa nhe!
