### ISSUE TITLE
Lỗi - Bệnh án ngoại trú theo đợt có nhập chứng nhận miễn FEES báo tiền thu bị âm

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#84]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongngu_phieuthu_amtien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1iwXjYnOG6hF2IFxesE9wtwEyRC6fnsjk/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018000922` - _**MaKB**_: `2209000071` - _**MaBA**_: `N2022005345` _**NgayKCB**_: `29/9/2022` - _**MaPhong**_: `CC02` - _**MaDV**_: `05` - _**ThangKT**_: `09` - _**NamKT**_: `2022`
###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh án ngoại trú thanh toán theo đợt khi nhập chứng nhận miễn cùng chi trả
-> Fees thu tiền bệnh án ngoại trú: tiền bh thanh bị double và tiền bệnh nhân trả bị âm.

có kèm link dữ liệu
```
form thu tiền bị âm
![image](https://user-images.githubusercontent.com/96155021/195816439-e839f77b-003b-4c19-92f0-b5a1f0405e94.png)

bảng kê
![image](https://user-images.githubusercontent.com/96155021/195816162-3c3b8edf-083d-408e-987f-10ad4df735fd.png)

**Comment by ongtrieuhau** [comment]
Cập nhật Fees: [3.22.1029.2](https://github.com/dh-hos/dhg.hospitalfees/commit/a0f66f42841ed3b0b349824d33c68c39a767d071)

**Comment by le-an-87** [comment]
đã fix!
