### ISSUE TITLE
Yêu cầu - Bổ sung hàm lấy lại thông tin hóa đơn đã được tạo.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#85]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79035`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Gò vấp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvgovap_102022`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)
BV đề nghị bổ sung thêm chức năng lấy thông tin hóa đơn đã được tạo nhưng chưa trả kết quả về cho HIS được.
Mã KB: `2210000004`, Số ct nội bộ: `KT2.00004/10`, ngày phiếu thu: `01/10/2022`, tháng KT: `10`, năm KT: `2022`, chừng từ này đã được lập thành công trên cổng.
Dữ liệu đang cấu hình trang hddt chính thức.
Tài liệu tham khảo: Trang 52, **Phần 25-Truy vấn thông tin hoá đơn theo tập khoá Ikeys**
[EasyInvoice_TaiLieuTichHop_78_V7.docx](https://github.com/dh-hos/dhg.hospitalfees/files/9796379/EasyInvoice_TaiLieuTichHop_78_V7.docx)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.1028.1](https://github.com/dh-hos/dhg.hospitalfees/commit/542912fdac9b849c57dc1e9240c6fe37ef48aba0)
