### ISSUE TITLE
Yêu cầu - Ghi nhật ký thao tác cấu hình Hóa đơn điện tử

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#86]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV TMH Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_tmhct_hddtnhathuoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện Yêu cầu ghi nhật ký hoặt động trong from cấu hình hóa đơn điện tử, vì có tình trạng Cấu hình HDDT đang cấu hình **Lý do thu làm 1 dòng chi tiết hóa đơn**, nhưng khi lập HDDT(lập bằng Printer) thì lại đẩy chi tiết từng mặt hàng lên hệ thống HDDT, vài ngày là nó bị, nhưng khi trích dữ liệu về test thì không bị. Yêu cầu ghi nhật ký để xem có ai chỉnh cấu hình không?
![image](https://user-images.githubusercontent.com/99630883/196115372-1996bdbf-570f-46fb-b5e4-047e31baf739.png)
![image](https://user-images.githubusercontent.com/99630883/196119809-3a7c73c5-52a8-4891-947a-c0472363fdd7.png)

**Comment by ongtrieuhau** [comment]
Cập nhật Fees [3.22.1029.1](https://github.com/dh-hos/dhg.hospitalfees/commit/b4d83ebd196da036d448ab56e96018198bf60059)
