### ISSUE TITLE
Lỗi - Đồng bộ HDDT nhà thuốc tại form đồng bộ cuối ngày không theo cấu hình.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#87]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV TMH CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_tmhct_hddtnhathuoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `17/10/2022` - _**ThangKT**_: `10` - _**NamKT**_: `2022`- _**Số chừng từ thu**_: `NS6.00813/202210.BX`- _**Ngày chứng từ thu**_: `17/10/2022`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Fees có có cấu hình máy check Viện phí nhà thuốc.
Có cấu hình **Sử dụng lý do thu làm 1 dòng chi tiết hóa đơn.**
Trong dữ liệu **thuchi.nhathuoc=1**
Tại form Đồng bộ hóa đơn cuối ngày để thực hiện, nhưng lúc đồng bộ lại đẩy chi tiết tứng mặt hàng lên cổng HDDT.

![image](https://user-images.githubusercontent.com/99630883/197089543-c69e6787-88ce-4ca3-bf52-0fe1875a8cd1.png)
![image](https://user-images.githubusercontent.com/99630883/197089818-cb634799-5caa-4458-8733-e334c39fdb03.png)
![image](https://user-images.githubusercontent.com/99630883/197089633-7033fe82-0589-46d8-9b41-53c1fcc5f402.png)

**Comment by ongtrieuhau** [comment]
Cập nhật Fees [3.22.1028.2](https://github.com/dh-hos/dhg.hospitalfees/commit/1dbbc4796efa508bb57fec3929a900476a614160)
