### ISSUE TITLE
Lỗi - Cổng HDDT chưa trả về thông tin của HDDT.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#88]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79035`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Gò vấp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvgovap_102022`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `2210000004` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `10` - _**NamKT**_: `2022` - _**Số chứng từ thu**_: `KT2.00004/10` - _**Số biên lai**_:`0164778` - _**Ngày chứng từ thu**_: `01/10/2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)
Như yêu cầu của a @ongtrieuhau, theo GIT yêu cầu https://github.com/dh-hos/dhg.hospitalfees/issues/85, phần thông tin của BN phía trên lỗi đã tạo hóa đơn trên cổng rồi, nhưng cổng chưa trả thông tin về cho HIS.
Về trao đổi thông tin với bên easyinvoice thì có ung cấp tài liệu mô tả cho trường hợp này để lấy thông tin HDDT về.
Tài liệu tham khảo: Trang 52, Phần 25-Truy vấn thông tin hoá đơn theo tập khoá Ikeys

[EasyInvoice_TaiLieuTichHop_78_V7 (1).docx](https://github.com/dh-hos/dhg.hospitalfees/files/9849408/EasyInvoice_TaiLieuTichHop_78_V7.1.docx)

![image](https://user-images.githubusercontent.com/99630883/197462741-75583abf-1f4d-4bf7-a4bb-8900e996659c.png)
![image](https://user-images.githubusercontent.com/99630883/197463373-f9b1953c-9075-442e-a972-5159b00a8d79.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.1028.1](https://github.com/dh-hos/dhg.hospitalfees/commit/542912fdac9b849c57dc1e9240c6fe37ef48aba0)
