### ISSUE TITLE
Yêu cầu - Hỗ trợ mẫu báo cáo tổng hợp theo dịch vụ  đặc thù BV Phổi DT

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalfees#90]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87115`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Phổi Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphoidt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Bệnh viện nhờ hỗ trợ Bảng kê-> Tổng hợp theo dịch vụ theo đặc thù (Hình bên dưới)
![image](https://user-images.githubusercontent.com/97272364/199481429-87740a03-a1e9-4c37-b606-38dd2f421405.png)

```

**Comment by ongtrieuhau** [comment]
Gửi link dữ liệu vào @hvtuan1987

**Comment by nghivanbi** [comment]
Này @ongtrieuhau  trực tiếp lấy yêu cầu và hoàn thành báo cáo này trước ngày 07/11/2022

**Comment by ongtrieuhau** [comment]
Cập nhật Fees [3.22.1103.1](https://github.com/dh-hos/dhg.hospitalfees/commit/94ab0b5399340211e76d902ad4a874c2b9fceeb5) nhé @hvtuan1987
