### ISSUE TITLE
Yêu cầu - Bổ sung thay đổi index khi đồng bộ HDDT.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalfees#95]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_phusan_thutudo`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl).

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Theo yêu cầu phía bên cty VAT thì lúc thực hiện đẩy dữ liệu lên đồng bộ HDDT, **nếu nội dung có nhiều sản phẩm 2 dòng trở lên thì cái thẻ **"index"** phải tăng dần 1,2,3,4,.....**
Hiện tại Fees đang đẩy lên nếu có nhiều dòng nội dung đều là 1 (ví dụ json ở dưới), yêu cầu tăng dần 1,2,3,4,............

Mã KB: 2210002638
Số chứng từ thu: TC7.00003/10
Ngày KB: 10/11/2022

{
   "idTransaction": "WKBF2VL9KQ",
   "transactionId": "WKBF2VL9KQ",
   "id": "WKBF2VL9KQ",
   "erpId": "WKBF2VL9KQ",
   "userNameCreator": "Quản trị hệ thống",
   "creatorErp": "Quản trị hệ thống",
   "idBuyer": "2022082710",
   "buyerCode": "2022082710",
   "idBuyerGroup": "2022082710",
   "buyerGroupName": "NGOẠI TRÚ",
   "currency": "VND",
   "invoiceDetails": [
      {
         "idProduct": "NHA",
         "idUnit": "AAI",
         "id": 1,
         "productType": 1,
         **"index": 1**,
         "discountAmountBeforeTax": 0,
         "discountAmount": 0,
         "discountPercentBeforeTax": 0,
         "discountPercent": 0,
         "paymentAmount": 120400,
         "productId": "XBD",
         "productCode": "XBD",
         "productName": "20.00BHYT (Siêu âm:222,000; Xét nghiệm:341,300; Công khám:38,700)",
         "unitName": "Lần",
         "unitPrice": 120400,
         "quantity": 1,
         "amount": 120400,
         "vatPercent": 0,
         "vatPercentDisplay": "0",
         "vatAmount": 0,
         "note": ""
      },
      {
         "idProduct": "JSK",
         "idUnit": "HKF",
         "id": 1,
         "productType": 1,
         **"index": 1**,
         "discountAmountBeforeTax": 0,
         "discountAmount": 0,
         "discountPercentBeforeTax": 0,
         "discountPercent": 0,
         "paymentAmount": 38000,
         "productId": "MJL",
         "productCode": "MJL",
         "productName": "Chi phí dịch vụ(Siêu âm:38,000)",
         "unitName": "Lần",
         "unitPrice": 38000,
         "quantity": 1,
         "amount": 38000,
         "vatPercent": 0,
         "vatPercentDisplay": "0",
         "vatAmount": 0,
         "note": ""
      }
   ],
   "invoiceTaxBreakdowns": [],
   "invoiceDate": "2022-11-10",
   "note": "",
   "templateNo": "2",
   "serialNo": "C22TND",
   "invoiceTypeCode": "02GTTT",
   "exchangeRate": 1,
   "paymentMethod": "TM",
   "paymentDate": "2022-11-10T09:16:03.938947+07:00",
   "paymentAmountWords": "Một trăm năm mươi tám ngàn bốn trăm đồng chẵn",
   "totalAmount": 158400,
   "totalVatAmount": 0,
   "totalPaymentAmount": 158400,
   "totalDiscountAmount": 0,
   "totalDiscountAmountBeforeTax": 0,
   "totalDiscountPercentAfterTax": 0,
   "totalDiscountAmountAfterTax": 0,
   "buyerGroupCode": "0",
   "buyerEmail": "",
   "buyerFullName": "Test Test",
   "buyerLegalName": "Test Test",
   "buyerTaxCode": "",
   "buyerAddressLine": "Huyện An Phú, An Giang.",
   "buyerPostalCode": "",
   "buyerDistrictName": "",
   "buyerCityName": "",
   "buyerCountryCode": "VN",
   "buyerPhoneNumber": "",
   "buyerFaxNumber": "",
   "buyerBankName": "",
   "buyerBankAccount": "",
   "invoiceHeaderExtras": null,
   "invoiceDetailExtras": null
}

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.1110.1](https://github.com/dh-hos/dhg.hospitalfees/commit/877e8b4ce531c52ae6e2e0002e83e0fe5559e672)
